// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

declare global {

    // wshrpc.ActiveWorkItem
    type ActiveWorkItem = {
        project: string;
        kind: string;
        title: string;
        detail?: string;
        ts: number;
        navtarget?: string;
        workerorefs?: string[];
        mode?: string;
    };

    // baseds.AgentAnswerItem
    type AgentAnswerItem = {
        selectedindexes?: number[];
        text?: string;
    };

    // baseds.AgentAskData
    type AgentAskData = {
        oref: string;
        askid: string;
        questions?: AgentAskQuestion[];
        ts?: number;
        cleared?: boolean;
        prose?: boolean;
        note?: string;
        hold?: boolean;
    };

    // baseds.AgentAskOption
    type AgentAskOption = {
        label: string;
        description?: string;
        preview?: string;
    };

    // baseds.AgentAskQuestion
    type AgentAskQuestion = {
        question: string;
        header?: string;
        multiselect?: boolean;
        options?: AgentAskOption[];
    };

    // wshrpc.AgentControlMsg
    type AgentControlMsg = {
        text?: string;
        compact?: string;
        midturn?: boolean;
    };

    // wshrpc.AgentInfo
    type AgentInfo = {
        tabid: string;
        name: string;
        projectpath: string;
        project: string;
        runid: string;
        harness: string;
        state: string;
    };

    // baseds.AgentStatusData
    type AgentStatusData = {
        oref: string;
        state: string;
        detail?: string;
        agent?: string;
        model?: string;
        cwd?: string;
        sessionid?: string;
        provider?: string;
        title?: string;
        step?: string;
        committed?: boolean;
        transcriptpath?: string;
        ts: number;
        usage?: AgentUsage;
    };

    // wshrpc.AgentSyncAction
    type AgentSyncAction = {
        kind: string;
        runtime: string;
        path: string;
        detail?: string;
    };

    // wshrpc.AgentSyncHarness
    type AgentSyncHarness = {
        runtime: string;
        label: string;
        path: string;
        present: boolean;
        steering: string;
        skillsmanaged: number;
        skillsunmanaged: number;
        note?: string;
    };

    // wshrpc.AgentSyncSkill
    type AgentSyncSkill = {
        name: string;
        description?: string;
        states: {[key: string]: string};
        deltas?: {[key: string]: string[]};
    };

    // wshrpc.AgentSyncSkillColumn
    type AgentSyncSkillColumn = {
        runtime: string;
        label: string;
        present: boolean;
    };

    // wshrpc.AgentSyncSkillMove
    type AgentSyncSkillMove = {
        runtime: string;
        name: string;
        from: string;
        seed: boolean;
        keys?: string[];
        files?: string[];
        bodydiff: boolean;
    };

    // wshrpc.AgentTranscriptUpdate
    type AgentTranscriptUpdate = {
        lines: string[];
    };

    // baseds.AgentUsage
    type AgentUsage = {
        contextpct?: number;
        contextmax?: number;
        costusd?: number;
        fivehourpct?: number;
        fivehourreset?: number;
        weekpct?: number;
        weekreset?: number;
        account?: string;
    };

    // wshrpc.AmbientDecision
    type AmbientDecision = {
        dossierid: string;
        id: string;
        title: string;
        created: number;
    };

    // wshrpc.AmbientEdge
    type AmbientEdge = {
        oref: string;
        dossierid: string;
        provenance: string;
        bucket: string;
        state: string;
    };

    // wshrpc.AmbientTask
    type AmbientTask = {
        id: string;
        label: string;
    };

    // wshrpc.AskRtnData
    type AskRtnData = {
        askid: string;
        answers?: AgentAnswerItem[];
        cancelled?: boolean;
    };

    // wshrpc.AttentionItem
    type AttentionItem = {
        kind: string;
        key: string;
        channelid?: string;
        channelname?: string;
        runid?: string;
        source: string;
        text: string;
        action: string;
        phaseidx: number;
        waitingsince: number;
        taskid?: string;
        retry?: boolean;
        oref?: string;
        effortoid?: string;
        chunklabel?: string;
        why?: string;
        cites?: string[];
    };

    // wshrpc.BackgroundAgentData
    type BackgroundAgentData = {
        sessionid: string;
        cwd: string;
        kind: string;
        name: string;
        state: string;
        startedts: number;
    };

    // baseds.Badge
    type Badge = {
        badgeid: string;
        icon: string;
        color?: string;
        priority: number;
        pidlinked?: boolean;
    };

    // baseds.BadgeEvent
    type BadgeEvent = {
        oref: string;
        clear?: boolean;
        clearall?: boolean;
        clearbyid?: string;
        badge?: Badge;
    };

    // waveobj.BaseCheck
    type BaseCheck = {
        state: string;
        commit?: string;
        detail?: string;
    };

    // waveobj.Block
    type Block = WaveObj & {
        parentoref?: string;
        runtimeopts?: RuntimeOpts;
        stickers?: StickerType[];
        subblockids?: string[];
    };

    // blockcontroller.BlockControllerRuntimeStatus
    type BlockControllerRuntimeStatus = {
        blockid: string;
        version: number;
        shellprocstatus?: string;
        shellprocconnname?: string;
        shellprocexitcode: number;
        lastoutputts?: number;
    };

    // waveobj.BlockDef
    type BlockDef = {
        files?: {[key: string]: FileDef};
        meta?: MetaType;
    };

    // wshrpc.BlocksListEntry
    type BlocksListEntry = {
        windowid: string;
        workspaceid: string;
        tabid: string;
        blockid: string;
        meta: MetaType;
    };

    // wshrpc.BlocksListRequest
    type BlocksListRequest = {
        windowid?: string;
        workspaceid?: string;
    };

    // wshrpc.BranchInfo
    type BranchInfo = {
        name: string;
        age: string;
        remote?: boolean;
    };

    // wshrpc.CaptureEffortsStatus
    type CaptureEffortsStatus = {
        active: number;
        chunksdone: number;
        chunkstotal: number;
    };

    // wshrpc.CaptureStatus
    type CaptureStatus = {
        notecounts?: {[key: string]: number};
        efforts: CaptureEffortsStatus;
    };

    // waveobj.Channel
    type Channel = WaveObj & {
        name: string;
        projectpath?: string;
        createdts: number;
    };

    // waveobj.ChannelMessage
    type ChannelMessage = WaveObj & {
        channeloid?: string;
        id: string;
        kind: string;
        author: string;
        text: string;
        reforef?: string;
        ts: number;
        data?: string;
    };

    // waveobj.ChunkWorkRef
    type ChunkWorkRef = {
        kind: string;
        oref: string;
        ts: number;
    };

    // wshrpc.ClaudeAccountData
    type ClaudeAccountData = {
        id: string;
        label: string;
        createdts: number;
        email?: string;
    };

    // wshrpc.ClaudeProjectData
    type ClaudeProjectData = {
        path: string;
        name: string;
        lastactivets: number;
        sessions: number;
    };

    // waveobj.Client
    type Client = WaveObj & {
        windowids: string[];
        hasoldhistory?: boolean;
        tempoid?: string;
        installid?: string;
    };

    // workspaceservice.CloseTabRtnType
    type CloseTabRtnType = {
        closewindow?: boolean;
        newactivetabid?: string;
    };

    // wshrpc.CommandAckRunData
    type CommandAckRunData = {
        channelid: string;
        runid: string;
        land?: boolean;
    };

    // wshrpc.CommandAdvanceRunData
    type CommandAdvanceRunData = {
        channelid: string;
        runid: string;
        phaseidx: number;
        action: string;
        artifacts?: string[];
        verdict?: string;
        note?: string;
        commit?: string;
        report?: string;
        holdland?: boolean;
        forceland?: boolean;
    };

    // wshrpc.CommandAgentControlData
    type CommandAgentControlData = {
        oref: string;
    };

    // wshrpc.CommandAgentSyncAdoptData
    type CommandAgentSyncAdoptData = {
        apply?: boolean;
        keep?: {[key: string]: string};
    };

    // wshrpc.CommandAgentSyncAdoptRtnData
    type CommandAgentSyncAdoptRtnData = {
        moves?: AgentSyncSkillMove[];
        unresolved?: string[];
    };

    // wshrpc.CommandAgentSyncApplyData
    type CommandAgentSyncApplyData = {
        dryrun?: boolean;
    };

    // wshrpc.CommandAgentSyncApplyRtnData
    type CommandAgentSyncApplyRtnData = {
        actions: AgentSyncAction[];
    };

    // wshrpc.CommandAgentSyncSkillsRtnData
    type CommandAgentSyncSkillsRtnData = {
        skills: AgentSyncSkill[];
        columns: AgentSyncSkillColumn[];
        skillsroot: string;
        unmanaged: AgentSyncSkillMove[];
        unresolved: string[];
    };

    // wshrpc.CommandAgentSyncStatusRtnData
    type CommandAgentSyncStatusRtnData = {
        harnesses: AgentSyncHarness[];
        steeringdoc: string;
        skillsroot: string;
    };

    // wshrpc.CommandAgentSyncSteeringReadRtnData
    type CommandAgentSyncSteeringReadRtnData = {
        path: string;
        content: string;
        mtime: number;
    };

    // wshrpc.CommandAgentSyncSteeringWriteData
    type CommandAgentSyncSteeringWriteData = {
        content: string;
        basemtime: number;
    };

    // wshrpc.CommandAgentSyncSteeringWriteRtnData
    type CommandAgentSyncSteeringWriteRtnData = {
        mtime: number;
        conflict: boolean;
    };

    // wshrpc.CommandAgentsListRtnData
    type CommandAgentsListRtnData = {
        agents: AgentInfo[];
    };

    // wshrpc.CommandAgentsReadData
    type CommandAgentsReadData = {
        tab: string;
    };

    // wshrpc.CommandAgentsReadRtnData
    type CommandAgentsReadRtnData = {
        tabid: string;
        state: string;
        answer: string;
        answerts: number;
    };

    // wshrpc.CommandAgentsSendData
    type CommandAgentsSendData = {
        tab: string;
        text: string;
        fromoref: string;
    };

    // wshrpc.CommandAgentsSendRtnData
    type CommandAgentsSendRtnData = {
        tabid: string;
        sentts: number;
        midturn: boolean;
    };

    // wshrpc.CommandAgentsSetModelData
    type CommandAgentsSetModelData = {
        tab: string;
        model: string;
    };

    // wshrpc.CommandAgentsSetModelRtnData
    type CommandAgentsSetModelRtnData = {
        tabid: string;
        midturn: boolean;
        overstream: boolean;
    };

    // wshrpc.CommandAnswerAgentData
    type CommandAnswerAgentData = {
        oref: string;
        answers: AgentAnswerItem[];
    };

    // wshrpc.CommandAppendDossierDecisionData
    type CommandAppendDossierDecisionData = {
        dossierid: string;
        summary: string;
        rationale: string;
        links?: string[];
    };

    // wshrpc.CommandAppendDossierDecisionRtnData
    type CommandAppendDossierDecisionRtnData = {
        decisionid: string;
    };

    // wshrpc.CommandAskData
    type CommandAskData = {
        oref: string;
        questions: AgentAskQuestion[];
        wait?: boolean;
        prose?: boolean;
        hold?: boolean;
    };

    // wshrpc.CommandAuthenticateRtnData
    type CommandAuthenticateRtnData = {
        routeid: string;
        env?: {[key: string]: string};
        initscripttext?: string;
        rpccontext?: RpcContext;
    };

    // wshrpc.CommandAuthenticateTokenData
    type CommandAuthenticateTokenData = {
        token: string;
    };

    // wshrpc.CommandBlockInputData
    type CommandBlockInputData = {
        blockid: string;
        inputdata64?: string;
        signame?: string;
        termsize?: TermSize;
    };

    // wshrpc.CommandCancelRadarScanData
    type CommandCancelRadarScanData = {
        reportid: string;
    };

    // wshrpc.CommandCancelRunData
    type CommandCancelRunData = {
        channelid: string;
        runid: string;
    };

    // wshrpc.CommandClaudeAccountAddData
    type CommandClaudeAccountAddData = {
        label: string;
        token: string;
        email?: string;
    };

    // wshrpc.CommandClaudeAccountListRtnData
    type CommandClaudeAccountListRtnData = {
        accounts: ClaudeAccountData[];
        active: string;
        loginemail?: string;
    };

    // wshrpc.CommandClaudeAccountRemoveData
    type CommandClaudeAccountRemoveData = {
        id: string;
    };

    // wshrpc.CommandClaudeAccountRenameData
    type CommandClaudeAccountRenameData = {
        id: string;
        label: string;
    };

    // wshrpc.CommandClaudeAccountSetEmailData
    type CommandClaudeAccountSetEmailData = {
        id: string;
        email: string;
    };

    // wshrpc.CommandConsultData
    type CommandConsultData = {
        channelid: string;
        runtime: string;
        prompt: string;
        consultid: string;
    };

    // wshrpc.CommandControllerAppendOutputData
    type CommandControllerAppendOutputData = {
        blockid: string;
        data64: string;
    };

    // wshrpc.CommandControllerResyncData
    type CommandControllerResyncData = {
        forcerestart?: boolean;
        tabid: string;
        blockid: string;
        rtopts?: RuntimeOpts;
    };

    // wshrpc.CommandCreateBlockData
    type CommandCreateBlockData = {
        tabid: string;
        blockdef: BlockDef;
        rtopts?: RuntimeOpts;
    };

    // wshrpc.CommandCreateChannelData
    type CommandCreateChannelData = {
        name: string;
        projectpath?: string;
    };

    // wshrpc.CommandCreateChildRunData
    type CommandCreateChildRunData = {
        oref: string;
        goal: string;
        mode?: string;
    };

    // wshrpc.CommandCreateChildRunRtnData
    type CommandCreateChildRunRtnData = {
        runid: string;
    };

    // wshrpc.CommandCreateProjectData
    type CommandCreateProjectData = {
        name: string;
        path: string;
    };

    // wshrpc.CommandCreateRunData
    type CommandCreateRunData = {
        channelid: string;
        workspaceid: string;
        goal: string;
        runtime: string;
        model?: string;
        workerroute?: RoutePin;
        reviewerpicks?: boolean;
        reviewerroute?: RoutePin;
        orchestration?: string;
        parallelism?: number;
        playbookid?: string;
        mode?: string;
        landing?: string;
        radarorigin?: RunRadarOrigin;
        effortoid?: string;
        chunklabel?: string;
        deferstart?: boolean;
        planpath?: string;
        prototype?: string;
        origintabid?: string;
    };

    // wshrpc.CommandCreateRunRtnData
    type CommandCreateRunRtnData = {
        run: Run;
    };

    // wshrpc.CommandCreateWorktreeData
    type CommandCreateWorktreeData = {
        projectpath: string;
        branch: string;
    };

    // wshrpc.CommandCreateWorktreeRtnData
    type CommandCreateWorktreeRtnData = {
        worktreepath: string;
    };

    // wshrpc.CommandDagActionData
    type CommandDagActionData = {
        channelid: string;
        runid: string;
        taskid: string;
        action: string;
        model?: string;
        runtime?: string;
        notes?: string;
        downstream?: string;
        unverified?: string;
        downstreamfor?: string[];
        picks?: DagModelPick[];
    };

    // wshrpc.CommandDagAnswerData
    type CommandDagAnswerData = {
        channelid: string;
        runid: string;
        taskid: string;
        answers: AgentAnswerItem[];
        lead?: boolean;
    };

    // wshrpc.CommandDagAsksRtnData
    type CommandDagAsksRtnData = {
        asks: DagAskItem[];
    };

    // wshrpc.CommandDagMergeData
    type CommandDagMergeData = {
        channelid: string;
        runid: string;
        taskid: string;
    };

    // wshrpc.CommandDagPlanPreviewData
    type CommandDagPlanPreviewData = {
        planpath: string;
        projectpath?: string;
    };

    // wshrpc.CommandDagPlanPreviewRtnData
    type CommandDagPlanPreviewRtnData = {
        title?: string;
        verify?: string;
        setup?: string;
        check?: string;
        shape: DagPlanShape;
        tasks?: DagPlanPreviewTask[];
    };

    // wshrpc.CommandDagStatusData
    type CommandDagStatusData = {
        channelid: string;
        runid: string;
    };

    // wshrpc.CommandDagStatusRtnData
    type CommandDagStatusRtnData = {
        group: TaskGroup;
        digest: DagStatusDigest;
    };

    // wshrpc.CommandDagSubmitData
    type CommandDagSubmitData = {
        channelid: string;
        runid: string;
        title?: string;
        parallelism: number;
        tasks: TaskNode[];
        workerroute?: RoutePin;
        planpath?: string;
        specpath?: string;
        round?: boolean;
    };

    // wshrpc.CommandDeleteAgentSessionData
    type CommandDeleteAgentSessionData = {
        transcriptpath: string;
    };

    // wshrpc.CommandDeleteBlockData
    type CommandDeleteBlockData = {
        blockid: string;
    };

    // wshrpc.CommandDeleteChannelData
    type CommandDeleteChannelData = {
        channelid: string;
    };

    // wshrpc.CommandDeleteFileData
    type CommandDeleteFileData = {
        path: string;
        recursive: boolean;
    };

    // wshrpc.CommandDeleteProjectData
    type CommandDeleteProjectData = {
        name: string;
    };

    // wshrpc.CommandDocCompileData
    type CommandDocCompileData = {
        path: string;
    };

    // wshrpc.CommandDocCompileRtnData
    type CommandDocCompileRtnData = {
        rootpath: string;
        pdfpath?: string;
        ok: boolean;
        engine: string;
        durationms: number;
        pages: number;
        logtail?: string;
        firsterror?: string;
    };

    // wshrpc.CommandDocPdfFindData
    type CommandDocPdfFindData = {
        path: string;
    };

    // wshrpc.CommandDocPdfFindRtnData
    type CommandDocPdfFindRtnData = {
        rootpath: string;
        pdfpath?: string;
        source?: string;
        modtime?: number;
    };

    // wshrpc.CommandDossierEdgeData
    type CommandDossierEdgeData = {
        dossierid: string;
        runoref: string;
    };

    // wshrpc.CommandEffortChunkSeed
    type CommandEffortChunkSeed = {
        label: string;
        owner?: string;
    };

    // wshrpc.CommandEffortCreateData
    type CommandEffortCreateData = {
        title: string;
        project?: string;
        ticket?: string;
        parentoid?: string;
        chunks?: CommandEffortChunkSeed[];
    };

    // wshrpc.CommandEffortCreateRtnData
    type CommandEffortCreateRtnData = {
        effortoid: string;
    };

    // wshrpc.CommandEffortDeleteData
    type CommandEffortDeleteData = {
        effortoid: string;
    };

    // wshrpc.CommandEffortGetData
    type CommandEffortGetData = {
        effortoid: string;
        sourceblock?: string;
    };

    // wshrpc.CommandEffortGetRtnData
    type CommandEffortGetRtnData = {
        effort: Effort;
    };

    // wshrpc.CommandEffortListData
    type CommandEffortListData = {
        project?: string;
        includearchived?: boolean;
    };

    // wshrpc.CommandEffortListRtnData
    type CommandEffortListRtnData = {
        efforts: EffortSummary[];
    };

    // wshrpc.CommandEffortMutateData
    type CommandEffortMutateData = {
        effortoid: string;
        ops: EffortOp[];
        note?: string;
        author?: string;
        sourceblock?: string;
    };

    // wshrpc.CommandEffortMutateRtnData
    type CommandEffortMutateRtnData = {
        effort: Effort;
    };

    // wshrpc.CommandEventReadHistoryData
    type CommandEventReadHistoryData = {
        event: string;
        scope: string;
        maxitems: number;
    };

    // wshrpc.CommandFileCopyData
    type CommandFileCopyData = {
        srcuri: string;
        desturi: string;
        opts?: FileCopyOpts;
    };

    // wshrpc.CommandGetAgentTranscriptData
    type CommandGetAgentTranscriptData = {
        path: string;
        maxlines?: number;
        fromstart?: boolean;
    };

    // wshrpc.CommandGetAgentTranscriptRtnData
    type CommandGetAgentTranscriptRtnData = {
        lines: string[];
    };

    // wshrpc.CommandGetAttentionRtnData
    type CommandGetAttentionRtnData = {
        items: AttentionItem[];
    };

    // wshrpc.CommandGetBackgroundAgentsData
    type CommandGetBackgroundAgentsData = object;

    // wshrpc.CommandGetBackgroundAgentsRtnData
    type CommandGetBackgroundAgentsRtnData = {
        agents: BackgroundAgentData[];
    };

    // wshrpc.CommandGetCacheStatusData
    type CommandGetCacheStatusData = {
        path: string;
    };

    // wshrpc.CommandGetCacheStatusRtnData
    type CommandGetCacheStatusRtnData = {
        lastwritets?: number;
        onehour?: boolean;
    };

    // wshrpc.CommandGetChannelMessagesData
    type CommandGetChannelMessagesData = {
        channelid: string;
        before?: number;
        limit?: number;
    };

    // wshrpc.CommandGetChannelMessagesRtnData
    type CommandGetChannelMessagesRtnData = {
        messages: ChannelMessage[];
    };

    // wshrpc.CommandGetChannelRunChangesData
    type CommandGetChannelRunChangesData = {
        channelid: string;
        known?: {[key: string]: number};
    };

    // wshrpc.CommandGetChannelRunChangesRtnData
    type CommandGetChannelRunChangesRtnData = {
        runids: string[];
        runs: Run[];
    };

    // wshrpc.CommandGetChannelRunsData
    type CommandGetChannelRunsData = {
        channelid: string;
    };

    // wshrpc.CommandGetChannelRunsRtnData
    type CommandGetChannelRunsRtnData = {
        runs: Run[];
    };

    // wshrpc.CommandGetChannelsRtnData
    type CommandGetChannelsRtnData = {
        channels: Channel[];
    };

    // wshrpc.CommandGetClaudeQuotaRtnData
    type CommandGetClaudeQuotaRtnData = {
        fivehourpct?: number;
        fivehourreset?: number;
        weekpct?: number;
        weekreset?: number;
        capturedat?: number;
        source?: string;
        email?: string;
        retryat?: number;
    };

    // wshrpc.CommandGetConsumersRtnData
    type CommandGetConsumersRtnData = {
        totalbytes: number;
        availablebytes: number;
        windowms: number;
        agents: ConsumerAgent[];
        interfacebytes?: number;
        serverbytes?: number;
        hostbytes?: number;
        terminalsbytes?: number;
    };

    // wshrpc.CommandGetDossierData
    type CommandGetDossierData = {
        dossierid: string;
    };

    // wshrpc.CommandGetJarvisProfileData
    type CommandGetJarvisProfileData = {
        channelid: string;
    };

    // wshrpc.CommandGetJarvisProfileRtnData
    type CommandGetJarvisProfileRtnData = {
        global: JarvisProfile;
        override: ProfileOverride;
        resolved: JarvisProfile;
        principlediagnostics?: PrincipleDiagnostic[];
    };

    // wshrpc.CommandGetLatestResumeRtnData
    type CommandGetLatestResumeRtnData = {
        card?: ResumeCardData;
        runoref?: string;
        channeloid?: string;
        runstatus?: string;
        rungoal?: string;
    };

    // wshrpc.CommandGetMetaData
    type CommandGetMetaData = {
        oref: ORef;
    };

    // wshrpc.CommandGetRTInfoData
    type CommandGetRTInfoData = {
        oref: ORef;
    };

    // wshrpc.CommandGetRecentSessionsData
    type CommandGetRecentSessionsData = {
        windowdays?: number;
        limit?: number;
    };

    // wshrpc.CommandGetRecentSessionsRtnData
    type CommandGetRecentSessionsRtnData = {
        sessions: SessionInfo[];
    };

    // wshrpc.CommandGetSessionGroupData
    type CommandGetSessionGroupData = {
        cwd: string;
    };

    // wshrpc.CommandGetSessionGroupRtnData
    type CommandGetSessionGroupRtnData = {
        root: string;
        label: string;
    };

    // wshrpc.CommandGetSessionsActivityData
    type CommandGetSessionsActivityData = {
        windowdays?: number;
        limit?: number;
    };

    // wshrpc.CommandGetSessionsActivityRtnData
    type CommandGetSessionsActivityRtnData = {
        sessions: SessionActivity[];
    };

    // wshrpc.CommandGetSubagentsData
    type CommandGetSubagentsData = {
        path: string;
    };

    // wshrpc.CommandGetSubagentsRtnData
    type CommandGetSubagentsRtnData = {
        subagents: SubagentFileInfo[];
    };

    // wshrpc.CommandGetTranscriptTokensData
    type CommandGetTranscriptTokensData = {
        path: string;
    };

    // wshrpc.CommandGetTranscriptTokensRtnData
    type CommandGetTranscriptTokensRtnData = {
        tokens: number;
    };

    // wshrpc.CommandGetTranscriptUsageData
    type CommandGetTranscriptUsageData = {
        path: string;
    };

    // wshrpc.CommandGetTranscriptUsageRtnData
    type CommandGetTranscriptUsageRtnData = {
        buckets: UsageBucket[];
    };

    // wshrpc.CommandGetUsageStatsData
    type CommandGetUsageStatsData = {
        windowdays?: number;
    };

    // wshrpc.CommandGetUsageStatsRtnData
    type CommandGetUsageStatsRtnData = {
        buckets: UsageBucket[];
    };

    // wshrpc.CommandGetWindowTokensData
    type CommandGetWindowTokensData = {
        fivehourcutoff?: number;
        weekcutoff?: number;
    };

    // wshrpc.CommandGetWindowTokensRtnData
    type CommandGetWindowTokensRtnData = {
        fivehourtokens: number;
        weektokens: number;
    };

    // wshrpc.CommandGetWorkerCapacityRtnData
    type CommandGetWorkerCapacityRtnData = {
        totalbytes: number;
        availablebytes: number;
        perworkerbytes: number;
        heavybytes: number;
        measured: boolean;
        liveworkers: number;
        reservebytes: number;
        moreworkers: number;
    };

    // wshrpc.CommandGitChangesData
    type CommandGitChangesData = {
        cwd: string;
        ref?: string;
        sessionstartts?: number;
    };

    // wshrpc.CommandGitChangesRtnData
    type CommandGitChangesRtnData = {
        branch: string;
        statusz: string;
        numstat: string;
        isrepo: boolean;
        ref?: string;
        head?: string;
    };

    // wshrpc.CommandGitCommitChangesData
    type CommandGitCommitChangesData = {
        cwd: string;
        hash: string;
    };

    // wshrpc.CommandGitCommitChangesRtnData
    type CommandGitCommitChangesRtnData = {
        statusz: string;
        numstat: string;
        isrepo: boolean;
    };

    // wshrpc.CommandGitCompareChangesData
    type CommandGitCompareChangesData = {
        cwd: string;
        base: string;
        head: string;
        tips?: boolean;
    };

    // wshrpc.CommandGitCompareChangesRtnData
    type CommandGitCompareChangesRtnData = {
        statusz: string;
        numstat: string;
        isrepo: boolean;
    };

    // wshrpc.CommandGitDivergenceData
    type CommandGitDivergenceData = {
        cwd: string;
        base: string;
        head: string;
    };

    // wshrpc.CommandGitDivergenceRtnData
    type CommandGitDivergenceRtnData = {
        ahead: HistoryCommit[];
        behind: HistoryCommit[];
        mergebase: string;
        mergebasets: number;
        isrepo: boolean;
    };

    // wshrpc.CommandGitFetchData
    type CommandGitFetchData = {
        cwd: string;
        remote?: string;
    };

    // wshrpc.CommandGitFetchRtnData
    type CommandGitFetchRtnData = {
        fetchedat: number;
        failure?: GitFailure;
        isrepo: boolean;
    };

    // wshrpc.CommandGitFileAtRefData
    type CommandGitFileAtRefData = {
        cwd: string;
        ref: string;
        path: string;
        maxbytes?: number;
    };

    // wshrpc.CommandGitFileAtRefRtnData
    type CommandGitFileAtRefRtnData = {
        content: string;
        binary?: boolean;
        missing?: boolean;
        toolarge?: boolean;
        size?: number;
        isrepo: boolean;
    };

    // wshrpc.CommandGitGrepData
    type CommandGitGrepData = {
        cwd: string;
        query: string;
        regex?: boolean;
        wholeword?: boolean;
        casesensitive?: boolean;
        include?: string[];
        exclude?: string[];
    };

    // wshrpc.CommandGitGrepRtnData
    type CommandGitGrepRtnData = {
        matches: GitGrepMatch[];
        truncated?: boolean;
        invalidpattern?: boolean;
    };

    // wshrpc.CommandGitHistoryData
    type CommandGitHistoryData = {
        cwd: string;
        ref?: string;
        skip?: number;
        limit?: number;
        author?: string;
        grep?: string;
        path?: string;
    };

    // wshrpc.CommandGitHistoryRtnData
    type CommandGitHistoryRtnData = {
        commits: HistoryCommit[];
        head: string;
        isrepo: boolean;
        failure?: GitFailure;
    };

    // wshrpc.CommandGitListFilesData
    type CommandGitListFilesData = {
        cwd: string;
    };

    // wshrpc.CommandGitListFilesRtnData
    type CommandGitListFilesRtnData = {
        files: string[];
        ignored?: string[];
        isrepo: boolean;
        truncated?: boolean;
    };

    // wshrpc.CommandGitListIgnoredDirData
    type CommandGitListIgnoredDirData = {
        cwd: string;
        dir: string;
    };

    // wshrpc.CommandGitListIgnoredDirRtnData
    type CommandGitListIgnoredDirRtnData = {
        entries: string[];
    };

    // wshrpc.CommandGitListWorktreesData
    type CommandGitListWorktreesData = {
        cwd: string;
    };

    // wshrpc.CommandGitListWorktreesRtnData
    type CommandGitListWorktreesRtnData = {
        worktrees: GitWorktree[];
    };

    // wshrpc.CommandGitReviewPatchData
    type CommandGitReviewPatchData = {
        cwd: string;
        hash?: string;
        base?: string;
        maxbytes: number;
    };

    // wshrpc.CommandGitReviewPatchRtnData
    type CommandGitReviewPatchRtnData = {
        isrepo: boolean;
        files: ReviewPatchFile[];
    };

    // wshrpc.CommandJarvisCtxData
    type CommandJarvisCtxData = {
        blockoref?: string;
    };

    // wshrpc.CommandJarvisCtxRtnData
    type CommandJarvisCtxRtnData = {
        channelid?: string;
        runid?: string;
        dagoid?: string;
        goal?: string;
    };

    // wshrpc.CommandJarvisRunEventsData
    type CommandJarvisRunEventsData = {
        channelid: string;
        runid: string;
        limit?: number;
    };

    // wshrpc.CommandJarvisRunEventsRtnData
    type CommandJarvisRunEventsRtnData = {
        events: RunEvent[];
    };

    // wshrpc.CommandJarvisStateData
    type CommandJarvisStateData = {
        project?: string;
        sincems?: number;
    };

    // wshrpc.CommandJarvisStateRtnData
    type CommandJarvisStateRtnData = {
        state: WorkState;
    };

    // wshrpc.CommandJarvisStatusData
    type CommandJarvisStatusData = object;

    // wshrpc.CommandJarvisStatusRtnData
    type CommandJarvisStatusRtnData = {
        status: CaptureStatus;
    };

    // wshrpc.CommandLandRunData
    type CommandLandRunData = {
        channelid: string;
        runid: string;
        force?: boolean;
    };

    // wshrpc.CommandListBranchesData
    type CommandListBranchesData = {
        projectpath: string;
        includeremotes?: boolean;
    };

    // wshrpc.CommandListBranchesRtnData
    type CommandListBranchesRtnData = {
        branches: BranchInfo[];
        default?: string;
    };

    // wshrpc.CommandListDetachedEdgesData
    type CommandListDetachedEdgesData = {
        dossierid?: string;
        runoref?: string;
    };

    // wshrpc.CommandListDetachedEdgesRtnData
    type CommandListDetachedEdgesRtnData = {
        tasks: AmbientTask[];
        edges: AmbientEdge[];
    };

    // wshrpc.CommandListDevServersData
    type CommandListDevServersData = {
        cwd?: string;
        blockid?: string;
    };

    // wshrpc.CommandListDevServersRtnData
    type CommandListDevServersRtnData = {
        servers: Server[];
    };

    // wshrpc.CommandListDossiersRtnData
    type CommandListDossiersRtnData = {
        spaces: SpaceSummary[];
    };

    // wshrpc.CommandListHarnessesRtnData
    type CommandListHarnessesRtnData = {
        harnesses: HarnessInfo[];
    };

    // wshrpc.CommandListRadarReportsData
    type CommandListRadarReportsData = {
        projectpath?: string;
    };

    // wshrpc.CommandListRadarReportsRtnData
    type CommandListRadarReportsRtnData = {
        reports: RadarReport[];
    };

    // wshrpc.CommandListTaskDossiersRtnData
    type CommandListTaskDossiersRtnData = {
        dossiers: SpaceSummary[];
    };

    // wshrpc.CommandMessageData
    type CommandMessageData = {
        message: string;
    };

    // wshrpc.CommandPostChannelMessageData
    type CommandPostChannelMessageData = {
        channelid: string;
        kind: string;
        author: string;
        text: string;
        reforef?: string;
        data?: string;
    };

    // wshrpc.CommandReadVaultNoteData
    type CommandReadVaultNoteData = {
        id: string;
    };

    // wshrpc.CommandReadVaultNoteRtnData
    type CommandReadVaultNoteRtnData = {
        id: string;
        title: string;
        body: string;
        updated: number;
        project?: string;
    };

    // wshrpc.CommandRemoteFileStreamData
    type CommandRemoteFileStreamData = {
        path: string;
        byterange?: string;
        streammeta: StreamMeta;
    };

    // wshrpc.CommandRemoteListEntriesData
    type CommandRemoteListEntriesData = {
        path: string;
        opts?: FileListOpts;
    };

    // wshrpc.CommandRemoteListEntriesRtnData
    type CommandRemoteListEntriesRtnData = {
        fileinfo?: FileInfo[];
    };

    // wshrpc.CommandRemoveBackgroundAgentData
    type CommandRemoveBackgroundAgentData = {
        sessionid: string;
    };

    // wshrpc.CommandReportRunPhaseData
    type CommandReportRunPhaseData = {
        oref: string;
        action: string;
        artifacts?: string[];
        verdict?: string;
        note?: string;
        commit?: string;
        report?: string;
        holdland?: boolean;
        forceland?: boolean;
    };

    // wshrpc.CommandResolveAmbientRtnData
    type CommandResolveAmbientRtnData = {
        tasks: AmbientTask[];
        edges: AmbientEdge[];
        decisions: AmbientDecision[];
    };

    // wshrpc.CommandResolveDossierEdgesData
    type CommandResolveDossierEdgesData = {
        dossierid: string;
    };

    // wshrpc.CommandResolveDossierEdgesRtnData
    type CommandResolveDossierEdgesRtnData = {
        runs: GraphNode[];
        links: GraphLink[];
    };

    // wshrpc.CommandResolveFocusScopeData
    type CommandResolveFocusScopeData = {
        kind: string;
        id: string;
    };

    // wshrpc.CommandResolveIdsData
    type CommandResolveIdsData = {
        blockid: string;
        ids: string[];
    };

    // wshrpc.CommandResolveIdsRtnData
    type CommandResolveIdsRtnData = {
        resolvedids: {[key: string]: ORef};
    };

    // wshrpc.CommandRetryRadarClusteringData
    type CommandRetryRadarClusteringData = {
        reportid: string;
    };

    // wshrpc.CommandRunAnswerData
    type CommandRunAnswerData = {
        channelid: string;
        runid: string;
        answers: AgentAnswerItem[];
    };

    // wshrpc.CommandRunAskData
    type CommandRunAskData = {
        channelid: string;
        runid: string;
    };

    // wshrpc.CommandRunTranscriptPathData
    type CommandRunTranscriptPathData = {
        channelid: string;
        runid: string;
    };

    // wshrpc.CommandRunUsageData
    type CommandRunUsageData = {
        channelid: string;
        runid: string;
    };

    // wshrpc.CommandRunUsageRtnData
    type CommandRunUsageRtnData = {
        usage?: UsageRow[];
        sealed?: boolean;
    };

    // wshrpc.CommandScanClaudeProjectsRtnData
    type CommandScanClaudeProjectsRtnData = {
        projects: ClaudeProjectData[];
    };

    // wshrpc.CommandSealRunEvidenceData
    type CommandSealRunEvidenceData = {
        channelid: string;
        runid: string;
    };

    // wshrpc.CommandSetChannelProfileData
    type CommandSetChannelProfileData = {
        channelid: string;
        override: ProfileOverride;
    };

    // wshrpc.CommandSetChannelReadData
    type CommandSetChannelReadData = {
        channelid: string;
        ts: number;
    };

    // wshrpc.CommandSetChannelTierData
    type CommandSetChannelTierData = {
        channelid: string;
        tier: string;
    };

    // wshrpc.CommandSetDossierStatusData
    type CommandSetDossierStatusData = {
        dossierid: string;
        status: string;
    };

    // wshrpc.CommandSetGlobalProfileData
    type CommandSetGlobalProfileData = {
        profile: JarvisProfile;
    };

    // wshrpc.CommandSetMetaData
    type CommandSetMetaData = {
        oref: ORef;
        meta: MetaType;
    };

    // wshrpc.CommandSetRTInfoData
    type CommandSetRTInfoData = {
        oref: ORef;
        data: ObjRTInfo;
        delete?: boolean;
    };

    // wshrpc.CommandSetRadarFindingDispositionData
    type CommandSetRadarFindingDispositionData = {
        reportid: string;
        findingid: string;
        action: string;
        reason?: string;
        note?: string;
    };

    // wshrpc.CommandSetRunSettingsData
    type CommandSetRunSettingsData = {
        channelid: string;
        runid: string;
        parallelism?: number;
        workerroute?: RoutePin;
        reviewerpicks?: boolean;
        reviewerroute?: RoutePin;
    };

    // wshrpc.CommandStartRadarScanData
    type CommandStartRadarScanData = {
        projectpath: string;
    };

    // wshrpc.CommandStartRadarScanRtnData
    type CommandStartRadarScanRtnData = {
        report: RadarReport;
    };

    // wshrpc.CommandStopDevServerData
    type CommandStopDevServerData = {
        pid: number;
        createms: number;
    };

    // wshrpc.CommandStopRunWorkerData
    type CommandStopRunWorkerData = {
        channelid: string;
        runid: string;
        workeroref: string;
    };

    // wshrpc.CommandStreamAckData
    type CommandStreamAckData = {
        id: string;
        seq: number;
        rwnd: number;
        fin?: boolean;
        delay?: number;
        cancel?: boolean;
        error?: string;
    };

    // wshrpc.CommandStreamAgentTranscriptData
    type CommandStreamAgentTranscriptData = {
        path: string;
        taillines?: number;
    };

    // wshrpc.CommandStreamData
    type CommandStreamData = {
        id: string;
        seq: number;
        data64?: string;
        eof?: boolean;
        error?: string;
    };

    // wshrpc.CommandTermGetScrollbackLinesData
    type CommandTermGetScrollbackLinesData = {
        linestart: number;
        lineend: number;
        lastcommand: boolean;
    };

    // wshrpc.CommandTermGetScrollbackLinesRtnData
    type CommandTermGetScrollbackLinesRtnData = {
        totallines: number;
        linestart: number;
        lines: string[];
        lastupdated: number;
    };

    // wshrpc.CommandUiInvokeData
    type CommandUiInvokeData = {
        actionid: string;
        callerblockid?: string;
    };

    // wshrpc.CommandUiRevealData
    type CommandUiRevealData = {
        address: string;
        anchor?: string;
        callerblockid?: string;
        callercwd?: string;
    };

    // wshrpc.CommandUpdateHarnessData
    type CommandUpdateHarnessData = {
        runtime: string;
    };

    // wshrpc.CommandUpdateHarnessRtnData
    type CommandUpdateHarnessRtnData = {
        version: string;
    };

    // wshrpc.CommandVaultGraphRtnData
    type CommandVaultGraphRtnData = {
        nodes: GraphNode[];
        links: GraphLink[];
    };

    // wshrpc.CommandVaultSetRemoteData
    type CommandVaultSetRemoteData = {
        url: string;
    };

    // wshrpc.CommandVaultSyncData
    type CommandVaultSyncData = {
        wait?: boolean;
    };

    // wshrpc.CommandWriteTempFileData
    type CommandWriteTempFileData = {
        filename: string;
        data64: string;
    };

    // wconfig.ConfigError
    type ConfigError = {
        file: string;
        err: string;
    };

    // wconfig.ConnKeywords
    type ConnKeywords = {
        "display:order"?: number;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "cmd:env"?: {[key: string]: string};
        "cmd:initscript"?: string;
        "cmd:initscript.sh"?: string;
        "cmd:initscript.bash"?: string;
        "cmd:initscript.zsh"?: string;
        "cmd:initscript.pwsh"?: string;
        "cmd:initscript.fish"?: string;
    };

    // wshrpc.ConsultChunk
    type ConsultChunk = {
        text: string;
    };

    // wshrpc.ConsumerAgent
    type ConsumerAgent = {
        tabid: string;
        blockid: string;
        rambytes?: number;
        tokensread: boolean;
        tokens?: UsageBucket[];
        dag?: ConsumerDag;
    };

    // wshrpc.ConsumerDag
    type ConsumerDag = {
        channelid: string;
        runid: string;
        taskid: string;
    };

    // wshrpc.DagAskItem
    type DagAskItem = {
        taskid: string;
        askid?: string;
        owner?: string;
        deadline?: number;
        note?: string;
        questions: AgentAskQuestion[];
        blockoref: string;
        ts: number;
    };

    // wshrpc.DagDurationDigest
    type DagDurationDigest = {
        elapsedms: number;
        partial?: boolean;
        tasks?: DagTaskDuration[];
    };

    // wshrpc.DagLandedCommit
    type DagLandedCommit = {
        taskid: string;
        commit: string;
    };

    // wshrpc.DagModelPick
    type DagModelPick = {
        taskid: string;
        model: string;
        reason: string;
    };

    // wshrpc.DagNextStep
    type DagNextStep = {
        kind: string;
        taskids?: string[];
        blockingtaskids?: string[];
        actions?: string[];
        terminalstatus?: string;
    };

    // wshrpc.DagPlanPreviewTask
    type DagPlanPreviewTask = {
        id: string;
        title: string;
        lane: number;
        deps?: string[];
        model?: string;
    };

    // wshrpc.DagPlanShape
    type DagPlanShape = {
        tasks: number;
        lanes: number;
        longestchain: number;
    };

    // wshrpc.DagReportDigest
    type DagReportDigest = {
        workerms: number;
        commits?: DagLandedCommit[];
        unverified?: boolean;
        unverifiednotes?: DagUnverifiedNote[];
        answered: number;
        forwarded: number;
        usage?: UsageRow[];
    };

    // wshrpc.DagStatusCounts
    type DagStatusCounts = {
        total: number;
        done: number;
        running: number;
        stalled: number;
        dependencywaiting: number;
        attention: number;
        recoveredretry: number;
        mergeready: number;
    };

    // wshrpc.DagStatusDigest
    type DagStatusDigest = {
        dagversion: number;
        health: string;
        counts: DagStatusCounts;
        next: DagNextStep;
        tasks: DagTaskDigest[];
        durations: DagDurationDigest;
        report: DagReportDigest;
        shape?: DagPlanShape;
        final?: FinalStage;
        lanes?: string[][];
        told?: DagTold[];
        timing?: DagTimingDigest;
    };

    // wshrpc.DagTaskDigest
    type DagTaskDigest = {
        taskid: string;
        waitreason: string;
        blockingtaskids?: string[];
        humanactions?: string[];
        askid?: string;
        asksummary?: string;
        askts?: number;
        askdeadline?: number;
        freshnessts?: number;
        busy?: boolean;
        latesttool?: string;
        suspect?: string;
        verifystartedts?: number;
        verifylastline?: string;
        mergegatets?: number;
        recoveredretry?: boolean;
        mergestate: string;
        cleanupstate: string;
        reportsections?: string[];
        reviewverdict?: string;
        reviewround?: number;
        reviewnote?: string;
        reviewdownstream?: string;
        reviewunverified?: string;
    };

    // wshrpc.DagTaskDuration
    type DagTaskDuration = {
        taskid: string;
        runms?: number;
        mergewaitms?: number;
        cleanupms?: number;
        partial?: boolean;
    };

    // wshrpc.DagTimingActivity
    type DagTimingActivity = {
        key: string;
        startts: number;
        endts?: number;
    };

    // wshrpc.DagTimingDigest
    type DagTimingDigest = {
        startts: number;
        endts?: number;
        activities?: DagTimingActivity[];
        partial?: boolean;
    };

    // wshrpc.DagTold
    type DagTold = {
        taskid: string;
        ts: number;
        text: string;
    };

    // wshrpc.DagUnverifiedNote
    type DagUnverifiedNote = {
        taskid: string;
        text: string;
    };

    // wshrpc.DecisionCard
    type DecisionCard = {
        id: string;
        created: number;
        actor: string;
        provenance: string;
        status: string;
        links: string[];
        rationale: string;
    };

    // wshrpc.DossierDetail
    type DossierDetail = {
        id: string;
        ticket: string;
        objective: string;
        acceptance: string[];
        confidence: string;
        status: string;
        created: number;
        updated: number;
        state: string;
        blockers: string[];
        refs: string[];
        notes: string;
        decisions: DecisionCard[];
    };

    // waveobj.Effort
    type Effort = WaveObj & {
        title: string;
        project?: string;
        ticket?: string;
        status: string;
        parentoid?: string;
        chunks: EffortChunk[];
        notes?: EffortNote[];
        events?: EffortEvent[];
        createdts: number;
        updatedts: number;
    };

    // waveobj.EffortChunk
    type EffortChunk = {
        label: string;
        status: string;
        stage?: string;
        owner?: string;
        workrefs?: ChunkWorkRef[];
        notes?: EffortNote[];
        updatedts: number;
    };

    // wshrpc.EffortChunkSummary
    type EffortChunkSummary = {
        label: string;
        status: string;
        stage?: string;
        owner?: string;
        workrefs?: ChunkWorkRef[];
    };

    // waveobj.EffortEvent
    type EffortEvent = {
        ts: number;
        kind: string;
        label?: string;
        text?: string;
    };

    // wshrpc.EffortLastNote
    type EffortLastNote = {
        ts: number;
        text: string;
        chunk?: string;
        author?: string;
        session?: string;
    };

    // waveobj.EffortNote
    type EffortNote = {
        ts: number;
        text: string;
        edited?: boolean;
        author?: string;
        session?: string;
        run?: string;
    };

    // wshrpc.EffortOp
    type EffortOp = {
        op: string;
        title?: string;
        project?: string;
        ticket?: string;
        status?: string;
        parentoid?: string;
        chunk?: string;
        label?: string;
        at?: number;
        owner?: string;
        stage?: string;
        note?: string;
        notets?: number;
        kind?: string;
        oref?: string;
    };

    // wshrpc.EffortSummary
    type EffortSummary = {
        oref: string;
        title: string;
        project?: string;
        ticket?: string;
        status: string;
        parentoid?: string;
        chunks?: EffortChunkSummary[];
        done: number;
        total: number;
        activechunk?: string;
        updatedts: number;
        lastnote?: EffortLastNote;
    };

    // waveobj.EvidenceArtifact
    type EvidenceArtifact = {
        path: string;
        kind: string;
        size: number;
    };

    // waveobj.EvidenceDag
    type EvidenceDag = {
        tasks?: EvidenceDagTask[];
        answered: number;
        forwarded: number;
        told?: string[];
        leftbehind?: string[];
    };

    // waveobj.EvidenceDagTask
    type EvidenceDagTask = {
        taskid: string;
        label?: string;
        state: string;
        commit?: string;
        reviewrounds?: number;
        differs?: string;
        notverified?: string;
        reviewerunverified?: string;
        foundnotfixed?: string;
        forlead?: string;
        unstructured?: string;
    };

    // waveobj.EvidenceFile
    type EvidenceFile = {
        path: string;
        stat: string;
        add: number;
        del: number;
    };

    // waveobj.EvidenceVerif
    type EvidenceVerif = {
        cmd: string;
        result: string;
        detail?: string;
    };

    // wshrpc.FileCopyOpts
    type FileCopyOpts = {
        overwrite?: boolean;
        recursive?: boolean;
        merge?: boolean;
        timeout?: number;
    };

    // wshrpc.FileData
    type FileData = {
        info?: FileInfo;
        data64?: string;
        entries?: FileInfo[];
        at?: FileDataAt;
    };

    // wshrpc.FileDataAt
    type FileDataAt = {
        offset: number;
        size?: number;
    };

    // waveobj.FileDef
    type FileDef = {
        content?: string;
        meta?: {[key: string]: any};
    };

    // wshrpc.FileInfo
    type FileInfo = {
        path: string;
        dir?: string;
        name?: string;
        staterror?: string;
        notfound?: boolean;
        opts?: FileOpts;
        size?: number;
        meta?: {[key: string]: any};
        mode?: number;
        modestr?: string;
        modtime?: number;
        isdir?: boolean;
        supportsmkdir?: boolean;
        mimetype?: string;
        readonly?: boolean;
    };

    // wshrpc.FileListOpts
    type FileListOpts = {
        all?: boolean;
        offset?: number;
        limit?: number;
    };

    // wshrpc.FileOpts
    type FileOpts = {
        maxsize?: number;
        circular?: boolean;
        truncate?: boolean;
        append?: boolean;
    };

    // waveobj.FinalShot
    type FinalShot = {
        name: string;
        files: string[];
        steps?: FinalShotStep[];
    };

    // waveobj.FinalShotStep
    type FinalShotStep = {
        step: string;
        state: string;
        detail?: string;
    };

    // waveobj.FinalStage
    type FinalStage = {
        state: string;
        round: number;
        tree?: string;
        commit?: string;
        outdir?: string;
        detail?: string;
        unverified?: string[];
        verifierrunid?: string;
        respawns?: number;
        startedts?: number;
        step?: string;
        stepts?: number;
        output?: string;
        shots?: FinalShot[];
        shotsmanifest?: boolean;
    };

    // wconfig.FullConfigType
    type FullConfigType = {
        settings: SettingsType;
        defaultsettings: SettingsType;
        connections: {[key: string]: ConnKeywords};
        projects: {[key: string]: ProjectKeywords};
        configerrors: ConfigError[];
        version: string;
        buildtime: string;
    };

    // gitinfo.GitFailure
    type GitFailure = {
        command: string;
        exitcode: number;
        stderr: string;
    };

    // wshrpc.GitGrepMatch
    type GitGrepMatch = {
        path: string;
        line: number;
        text: string;
    };

    // wshrpc.GitWorktree
    type GitWorktree = {
        path: string;
        branch?: string;
        ismain?: boolean;
    };

    // wshrpc.GraphLink
    type GraphLink = {
        from: string;
        to: string;
        kind: string;
        provenance?: string;
        bucket?: string;
        state?: string;
    };

    // wshrpc.GraphNode
    type GraphNode = {
        id: string;
        kind: string;
        label: string;
        status?: string;
        updated?: number;
    };

    // wshrpc.HarnessInfo
    type HarnessInfo = {
        runtime: string;
        label: string;
        installed: boolean;
        version?: string;
        latestversion?: string;
        consultcapable: boolean;
        runworkercapable: boolean;
        leadcapable: boolean;
        routecapabilities?: RouteCapabilityInfo[];
    };

    // gitinfo.HistoryCommit
    type HistoryCommit = {
        hash: string;
        parents: string[];
        author: string;
        email: string;
        ts: number;
        subject: string;
        refs?: string[];
    };

    // waveobj.JarvisProfile
    type JarvisProfile = {
        principles?: Principle[];
        defaultmode?: string;
        parallelism?: number;
        workerroute?: RoutePin;
        reviewerpicks?: boolean;
        reviewerroute?: RoutePin;
        landing?: string;
    };

    // waveobj.MetaTSType
    type MetaType = {
        view?: string;
        controller?: string;
        file?: string;
        connection?: string;
        edit?: boolean;
        history?: string[];
        "display:name"?: string;
        "display:order"?: number;
        icon?: string;
        "cmd:*"?: boolean;
        cmd?: string;
        "cmd:interactive"?: boolean;
        "cmd:runonstart"?: boolean;
        "cmd:clearonstart"?: boolean;
        "cmd:runonce"?: boolean;
        "cmd:closeonexit"?: boolean;
        "cmd:closeonexitforce"?: boolean;
        "cmd:keeponexit"?: boolean;
        "cmd:closeonexitdelay"?: number;
        "cmd:nowsh"?: boolean;
        "cmd:args"?: string[];
        "cmd:shell"?: boolean;
        "cmd:jwt"?: boolean;
        "cmd:env"?: {[key: string]: string};
        "cmd:cwd"?: string;
        "cmd:initscript"?: string;
        "cmd:initscript.sh"?: string;
        "cmd:initscript.bash"?: string;
        "cmd:initscript.zsh"?: string;
        "cmd:initscript.pwsh"?: string;
        "cmd:initscript.fish"?: string;
        "editor:*"?: boolean;
        "editor:minimapenabled"?: boolean;
        "editor:stickyscrollenabled"?: boolean;
        "editor:wordwrap"?: boolean;
        "editor:fontsize"?: number;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "term:localshellpath"?: string;
        "term:localshellopts"?: string[];
        "term:scrollback"?: number;
        "term:allowbracketedpaste"?: boolean;
        "term:shiftenternewline"?: boolean;
        "term:macoptionismeta"?: boolean;
        "term:cursor"?: string;
        "term:cursorblink"?: boolean;
        "term:conndebug"?: string;
        "term:bellindicator"?: boolean;
        "term:osc52"?: string;
        "session:pinned"?: boolean;
        "session:agent"?: string;
        "session:label"?: string;
        "session:project"?: string;
        "session:effort"?: string;
        "session:collapsedgroups"?: string[];
        "session:helper"?: boolean;
        "app:loom"?: boolean;
        "agent:transcriptpath"?: string;
        "agent:loginemail"?: string;
        count?: number;
    };

    // tsgenmeta.MethodMeta
    type MethodMeta = {
        Desc: string;
        ArgNames: string[];
        ReturnDesc: string;
    };

    // wshrpc.NotifyCommandData
    type NotifyCommandData = {
        title: string;
        message: string;
        level: string;
    };

    // waveobj.ORef
    type ORef = string;

    // waveobj.ObjRTInfo
    type ObjRTInfo = {
        "shell:hascurcwd"?: boolean;
        "shell:state"?: string;
        "shell:type"?: string;
        "shell:version"?: string;
        "shell:uname"?: string;
        "shell:integration"?: boolean;
        "shell:omz"?: boolean;
        "shell:comp"?: string;
        "shell:inputempty"?: boolean;
        "shell:lastcmd"?: string;
        "shell:lastcmdexitcode"?: number;
    };

    // wshrpc.OpenFileData
    type OpenFileData = {
        path: string;
        edit?: boolean;
    };

    // wshrpc.PathCommandData
    type PathCommandData = {
        pathtype: string;
        openexternal: boolean;
    };

    // waveobj.PhaseTriage
    type PhaseTriage = {
        verdict: string;
        note?: string;
    };

    // waveobj.PlanReviewStage
    type PlanReviewStage = {
        state: string;
        round: number;
        runid?: string;
        findings?: string;
        respawns?: number;
        startedts?: number;
    };

    // waveobj.Point
    type Point = {
        x: number;
        y: number;
    };

    // waveobj.Principle
    type Principle = {
        id: string;
        text: string;
    };

    // waveobj.PrincipleDiagnostic
    type PrincipleDiagnostic = {
        code: string;
        principleid: string;
    };

    // waveobj.PrinciplePatch
    type PrinciplePatch = {
        additions?: Principle[];
        replacements?: {[key: string]: string};
        disabled?: string[];
    };

    // waveobj.ProfileOverride
    type ProfileOverride = {
        principles?: PrinciplePatch;
        route?: RoutePin;
        defaultmode?: string;
        parallelism?: number;
        workerroute?: RoutePin;
        reviewerpicks?: boolean;
        reviewerroute?: RoutePin;
        landing?: string;
    };

    // wconfig.ProjectKeywords
    type ProjectKeywords = {
        path?: string;
    };

    // wshrpc.ProjectWork
    type ProjectWork = {
        project: string;
        active?: ActiveWorkItem[];
        shipped?: ShippedItem[];
        events?: TimelineEvent[];
        delta?: TimelineEvent[];
    };

    // waveobj.RadarAudit
    type RadarAudit = {
        commit: string;
        subject: string;
        committs: number;
        files: string[];
        status: string;
        rootcause?: string;
        hitcount?: number;
        keptcount?: number;
        error?: string;
        resolvedmodel?: string;
        totaltokens?: number;
        cachereadtokens?: number;
        durationms?: number;
        rawresponse?: string;
    };

    // waveobj.RadarDisposition
    type RadarDisposition = {
        action: string;
        reason?: string;
        note?: string;
        ts: number;
        user?: string;
        evidencerev?: string;
    };

    // waveobj.RadarFinding
    type RadarFinding = {
        id: string;
        fingerprint: string;
        group: string;
        riskkind: string;
        subsystem: string;
        risk: string;
        why: string;
        severity: string;
        signalids: string[];
        files: string[];
        mission: string;
        disposition?: RadarDisposition;
        investigation?: RadarInvestigation;
        misscount?: number;
        sourcecommit?: string;
        sourcesubject?: string;
        rootcause?: string;
        sites?: RadarSite[];
    };

    // waveobj.RadarInvestigation
    type RadarInvestigation = {
        runid: string;
        channelid: string;
        status: string;
        startedts: number;
        completedts?: number;
        summary?: string;
        filestouched?: number;
        addtotal?: number;
        deltotal?: number;
        verifspass?: number;
        verifsfail?: number;
    };

    // waveobj.RadarReport
    type RadarReport = WaveObj & {
        projectname: string;
        projectpath: string;
        status: string;
        phase?: string;
        starthead?: string;
        endhead?: string;
        startdirty?: string;
        enddirty?: string;
        prevreportid?: string;
        prevhead?: string;
        windowstartts?: number;
        windowendts?: number;
        startedts: number;
        completedts?: number;
        fatalerror?: string;
        clustererror?: string;
        configuredmodel?: string;
        resolvedmodel?: string;
        totaltokens?: number;
        candidates?: RadarSignal[];
        signals?: RadarSignal[];
        findings?: RadarFinding[];
        clusterstartedts?: number;
        audits?: RadarAudit[];
    };

    // waveobj.RadarSignal
    type RadarSignal = {
        id: string;
        collector: string;
        sourceref: string;
        observedts: number;
        paths?: string[];
        subsystem?: string;
        summary: string;
        facts?: {[key: string]: any};
        snippet?: string;
        contenthash: string;
    };

    // waveobj.RadarSite
    type RadarSite = {
        line: number;
        trigger: string;
        actual: string;
        expected: string;
        whynotcovered: string;
    };

    // wshrpc.ResumeCardData
    type ResumeCardData = {
        taskId: string;
        summary: string;
        status: string;
        updated: number;
    };

    // gitinfo.ReviewPatchFile
    type ReviewPatchFile = {
        path: string;
        oldpath?: string;
        diff?: string;
        untracked?: boolean;
        content?: string;
        toolarge?: boolean;
        size?: number;
    };

    // wshrpc.RouteCapabilityInfo
    type RouteCapabilityInfo = {
        runtime: string;
        model?: string;
        resolvedmodel: string;
        provider?: string;
        contexthint?: string;
        default?: boolean;
    };

    // waveobj.RoutePin
    type RoutePin = {
        runtime: string;
        model?: string;
        tier?: string;
    };

    // wshrpc.RpcContext
    type RpcContext = {
        sockname?: string;
        routeid: string;
        procroute?: boolean;
        blockid?: string;
        conn?: string;
        isrouter?: boolean;
    };

    // wshutil.RpcMessage
    type RpcMessage = {
        command?: string;
        reqid?: string;
        resid?: string;
        timeout?: number;
        route?: string;
        source?: string;
        cont?: boolean;
        cancel?: boolean;
        error?: string;
        datatype?: string;
        data?: any;
    };

    // wshrpc.RpcOpts
    type RpcOpts = {
        timeout?: number;
        noresponse?: boolean;
        route?: string;
    };

    // waveobj.Run
    type Run = WaveObj & {
        channeloid?: string;
        id: string;
        goal: string;
        runtime?: string;
        model?: string;
        playbookid?: string;
        mode?: string;
        workspaceid: string;
        projectpath: string;
        landpath?: string;
        basebranch?: string;
        basecommit?: string;
        endcommit?: string;
        report?: string;
        principles?: Principle[];
        status: string;
        phases: RunPhase[];
        radarorigin?: RunRadarOrigin;
        createdts: number;
        completedts?: number;
        evidence?: RunEvidence;
        land?: RunLand;
        verificationackts?: number;
        parentleadoref?: string;
        origintabid?: string;
        origintranscript?: string;
        effortref?: RunEffortRef;
        dagoref?: string;
        sessionid?: string;
        leadsessionids?: string[];
        taskid?: string;
        review?: boolean;
        stagerole?: string;
        branch?: string;
        workerroute?: RoutePin;
        reviewerpicks?: boolean;
        reviewerroute?: RoutePin;
        orchestration?: string;
        parallelism?: number;
        prototype?: string;
        plangatepending?: boolean;
        planfeedback?: string;
    };

    // waveobj.RunEffortRef
    type RunEffortRef = {
        effortoid: string;
        chunklabel: string;
    };

    // waveobj.RunEvent
    type RunEvent = {
        id: string;
        runid: string;
        channelid: string;
        ts: number;
        kind: string;
        phaseidx?: number;
        detail?: string;
    };

    // wshrpc.RunEventData
    type RunEventData = {
        channelid: string;
        runid: string;
        event: RunEvent;
    };

    // waveobj.RunEvidence
    type RunEvidence = {
        capturedts: number;
        hash: string;
        summary?: string;
        files?: EvidenceFile[];
        addtotal: number;
        deltotal: number;
        verifs?: EvidenceVerif[];
        artifacts?: EvidenceArtifact[];
        runtimems: number;
        durationms: number;
        harness?: string;
        model?: string;
        usage?: UsageRow[];
        verification?: RunVerification;
        dag?: EvidenceDag;
    };

    // waveobj.RunLand
    type RunLand = {
        state: string;
        reason?: string;
        commit?: string;
        notes?: string[];
        dismissed?: boolean;
    };

    // waveobj.RunPhase
    type RunPhase = {
        kind: string;
        skill?: string;
        state: string;
        gate?: boolean;
        freshctx?: boolean;
        held?: boolean;
        triage?: PhaseTriage;
        workerorefs?: string[];
        artifacts?: string[];
        startedts?: number;
        donets?: number;
    };

    // waveobj.RunRadarOrigin
    type RunRadarOrigin = {
        reportid: string;
        findingid: string;
        fingerprint: string;
    };

    // waveobj.RunSpec
    type RunSpec = {
        runtime?: string;
        model?: string;
        mode?: string;
        goal?: string;
    };

    // waveobj.RunVerification
    type RunVerification = {
        state: string;
        reasons?: string[];
    };

    // waveobj.RuntimeOpts
    type RuntimeOpts = {
        termsize?: TermSize;
        winsize?: WinSize;
    };

    // devservers.Server
    type Server = {
        pid: number;
        createms: number;
        ports: number[];
        name: string;
        cmdline: string;
        cwd: string;
        byagent: boolean;
        launchercmdline?: string;
    };

    // wshrpc.SessionActivity
    type SessionActivity = {
        id: string;
        runtime: string;
        projectpath: string;
        projectname: string;
        branch: string;
        task: string;
        model: string;
        tokenstotal: number;
        lastactivets: number;
        resumecommand: string;
        resumeargs?: string[];
        transcriptpath: string;
        status: string;
        startedts: number;
        durationms: number;
        events: SessionEvent[];
        runid?: string;
        channelid?: string;
        taskid?: string;
        role?: string;
    };

    // wshrpc.SessionEvent
    type SessionEvent = {
        type: string;
        ts: number;
        text: string;
    };

    // wshrpc.SessionInfo
    type SessionInfo = {
        id: string;
        runtime: string;
        projectpath: string;
        projectname: string;
        branch: string;
        task: string;
        model: string;
        tokenstotal: number;
        lastactivets: number;
        resumecommand: string;
        transcriptpath: string;
        resumeargs?: string[];
    };

    // wconfig.SettingsType
    type SettingsType = {
        "app:*"?: boolean;
        "app:ctrlvpaste"?: boolean;
        "app:disablectrlshiftdisplay"?: boolean;
        "notify:*"?: boolean;
        "notify:os"?: boolean;
        "notify:toast"?: boolean;
        "notify:reply"?: boolean;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "term:disablewebgl"?: boolean;
        "term:localshellpath"?: string;
        "term:localshellopts"?: string[];
        "term:gitbashpath"?: string;
        "term:scrollback"?: number;
        "term:copyonselect"?: boolean;
        "term:allowbracketedpaste"?: boolean;
        "term:shiftenternewline"?: boolean;
        "term:macoptionismeta"?: boolean;
        "term:cursor"?: string;
        "term:cursorblink"?: boolean;
        "term:bellindicator"?: boolean;
        "term:osc52"?: string;
        "term:trimtrailingwhitespace"?: boolean;
        "memory:vaultpath"?: string;
        "headless:runtime"?: string;
        "headless:openroutercheapmodel"?: string;
        "jarvis:vaultpath"?: string;
        "editor:minimapenabled"?: boolean;
        "editor:stickyscrollenabled"?: boolean;
        "editor:wordwrap"?: boolean;
        "editor:fontsize"?: number;
        "editor:inlinediff"?: boolean;
        "window:*"?: boolean;
        "window:reducedmotion"?: boolean;
        "window:magnifiedblockopacity"?: number;
        "window:magnifiedblocksize"?: number;
        "window:magnifiedblockblursecondarypx"?: number;
        "conn:*"?: boolean;
        "conn:localhostdisplayname"?: string;
        "debug:*"?: boolean;
        "debug:pprofport"?: number;
        "debug:pprofmemprofilerate"?: number;
        "debug:webglstatus"?: boolean;
        "harness:preferredruntime"?: string;
        "harness:preferredmodel"?: string;
        "harness:updatecheck"?: boolean;
        "claude:*"?: boolean;
        "claude:activeaccount"?: string;
        "radar:auditruntime"?: string;
        "radar:auditmodel"?: string;
    };

    // wshrpc.ShippedItem
    type ShippedItem = {
        project: string;
        runoid: string;
        goal: string;
        summary?: string;
        files?: EvidenceFile[];
        verifs?: EvidenceVerif[];
        completedts: number;
        hasreport?: boolean;
        effortoid?: string;
        chunklabel?: string;
        mode?: string;
    };

    // wshrpc.SourceHealth
    type SourceHealth = {
        runs: boolean;
        sessions: boolean;
        dossiers: boolean;
        efforts: boolean;
        attention: string;
    };

    // wshrpc.SpaceScope
    type SpaceScope = {
        runorefs: string[];
        channeloids: string[];
        tabids: string[];
    };

    // wshrpc.SpaceSummary
    type SpaceSummary = {
        id: string;
        objective: string;
        ticket: string;
        status: string;
        updated: number;
    };

    // waveobj.StickerClickOptsType
    type StickerClickOptsType = {
        sendinput?: string;
        createblock?: BlockDef;
    };

    // waveobj.StickerDisplayOptsType
    type StickerDisplayOptsType = {
        icon: string;
        imgsrc: string;
        svgblob?: string;
    };

    // waveobj.StickerType
    type StickerType = {
        stickertype: string;
        style: {[key: string]: any};
        clickopts?: StickerClickOptsType;
        display: StickerDisplayOptsType;
    };

    // wshrpc.StreamMeta
    type StreamMeta = {
        id: string;
        rwnd: number;
        readerrouteid: string;
        writerrouteid: string;
    };

    // wshrpc.SubagentFileInfo
    type SubagentFileInfo = {
        agentid: string;
        transcriptpath: string;
        firstprompt: string;
        startedatms: number;
        done: boolean;
        model?: string;
    };

    // wps.SubscriptionRequest
    type SubscriptionRequest = {
        event: string;
        scopes?: string[];
        allscopes?: boolean;
    };

    // waveobj.Tab
    type Tab = WaveObj & {
        name: string;
        blockids: string[];
    };

    // waveobj.TaskGroup
    type TaskGroup = WaveObj & {
        id: string;
        runid: string;
        channelid: string;
        title?: string;
        parallelism: number;
        tasks: TaskNode[];
        status: string;
        failures: number;
        workerroute?: RoutePin;
        reviewerpicks?: boolean;
        reviewerroute?: RoutePin;
        mergerequired?: boolean;
        createdts: number;
        updatedts: number;
        plangate?: boolean;
        planapprovedts?: number;
        notifiedcondition?: string;
        usage?: UsageRow[];
        verify?: string;
        setup?: string;
        check?: string;
        basecheck?: BaseCheck;
        finalcmd?: string;
        prototype?: string;
        preamble?: string;
        effortoid?: string;
        planpath?: string;
        specpath?: string;
        planreview?: PlanReviewStage;
        final?: FinalStage;
        pastfinals?: FinalStage[];
    };

    // waveobj.TaskNode
    type TaskNode = {
        id: string;
        label?: string;
        description?: string;
        deps?: string[];
        chunks?: string[];
        gate?: boolean;
        state: string;
        runid?: string;
        released?: boolean;
        merged?: boolean;
        runspec?: RunSpec;
        modelsource?: string;
        pickreason?: string;
        lastactivity?: number;
        cpusample?: number;
        cpusamplets?: number;
        busyts?: number;
        askts?: number;
        latesttool?: string;
        progresshash?: string;
        progressts?: number;
        progresscheckts?: number;
        suspectts?: number;
        suspectreason?: string;
        flaggedfailures?: string[];
        stallretries?: number;
        firstactivity?: number;
        toldts?: number;
        attempts?: number;
        lastfailurekind?: string;
        escalations?: number;
        cleanuppending?: boolean;
        cleanuperror?: string;
        cleanupattempts?: number;
        verifyerror?: string;
        verifyoutput?: string;
        verifystartedts?: number;
        verifydeferred?: boolean;
        mergeerror?: string;
        mergefailures?: number;
        reviewrunid?: string;
        reviewspawnedts?: number;
        reviewrespawns?: number;
        reviewround?: number;
        reviewverdict?: string;
        reviewnote?: string;
        reviewdownstream?: string;
        reviewunverified?: string;
        reviewdownstreamfor?: string[];
        reviewbase?: string;
        reviewcommit?: string;
        leadguidance?: string;
        leadnotes?: string[];
        leadtold?: string[];
    };

    // waveobj.TermSize
    type TermSize = {
        rows: number;
        cols: number;
    };

    // wshrpc.TimelineEvent
    type TimelineEvent = {
        ts: number;
        kind: string;
        project?: string;
        title: string;
        detail?: string;
        navtarget?: string;
    };

    // waveobj.UIContext
    type UIContext = {
        windowid: string;
        activetabid: string;
    };

    // wshrpc.UiAction
    type UiAction = {
        id: string;
        label: string;
        group: string;
        destructive?: boolean;
    };

    // wshrpc.UiState
    type UiState = {
        surface: string;
        busy: boolean;
        modalopen: boolean;
        selection: string[];
        actions: UiAction[];
    };

    // wshrpc.UsageBucket
    type UsageBucket = {
        harness: string;
        provider: string;
        model: string;
        day: string;
        input: number;
        output: number;
        reasoning: number;
        cacheread: number;
        cachecreate: number;
        cachecreate1h: number;
        reportedcostusd?: number;
        msgs: number;
    };

    // waveobj.UsageRow
    type UsageRow = {
        role: string;
        taskid?: string;
        model?: string;
        input: number;
        output: number;
        cacheread: number;
        cachewrite: number;
        cachewrite1h: number;
        msgs: number;
        missing?: boolean;
    };

    // wshrpc.VaultStatusRtnData
    type VaultStatusRtnData = {
        off?: string;
        remoteurl?: string;
        lastsuccessts?: number;
        lasterror?: string;
        running?: boolean;
        conflicts?: string[];
        malformedefforts?: string[];
    };

    // baseds.VolunteerData
    type VolunteerData = {
        class: string;
        id: string;
        at: number;
        title: string;
        text: string;
        sourcetype?: string;
        ref?: string;
        anchor?: string;
    };

    type WSCommandType = {
        wscommand: string;
    } & ( WSRpcCommand );

    // eventbus.WSEventType
    type WSEventType = {
        eventtype: string;
        oref?: string;
        data: any;
    };

    // wps.WSFileEventData
    type WSFileEventData = {
        zoneid: string;
        filename: string;
        fileop: string;
        data64: string;
    };

    // webcmd.WSRpcCommand
    type WSRpcCommand = {
        wscommand: "rpc";
        message: RpcMessage;
    };

    // wconfig.WatcherUpdate
    type WatcherUpdate = {
        fullconfig: FullConfigType;
    };


    // filestore.WaveFile
    type WaveFile = {
        zoneid: string;
        name: string;
        opts: FileOpts;
        createdts: number;
        size: number;
        modts: number;
        meta: {[key: string]: any};
    };

    // wshrpc.WaveInfoData
    type WaveInfoData = {
        version: string;
        clientid: string;
        buildtime: string;
        configdir: string;
        datadir: string;
    };

    // waveobj.WaveObj
    type WaveObj = {
        otype: string;
        oid: string;
        version: number;
        meta: MetaType;
    };

    // waveobj.WaveObjUpdate
    type WaveObjUpdate = {
        updatetype: string;
        otype: string;
        oid: string;
        obj?: WaveObj;
    };

    // waveobj.Window
    type WaveWindow = WaveObj & {
        workspaceid: string;
        isnew?: boolean;
        pos: Point;
        winsize: WinSize;
        lastfocusts: number;
    };

    // service.WebCallType
    type WebCallType = {
        service: string;
        method: string;
        uicontext?: UIContext;
        args: any[];
    };

    // service.WebReturnType
    type WebReturnType = {
        success?: boolean;
        error?: string;
        data?: any;
        updates?: WaveObjUpdate[];
    };

    // waveobj.WinSize
    type WinSize = {
        width: number;
        height: number;
    };

    // wshrpc.WorkState
    type WorkState = {
        projects?: ProjectWork[];
        efforts?: EffortSummary[];
        sources: SourceHealth;
    };

    // waveobj.Workspace
    type Workspace = WaveObj & {
        name?: string;
        icon?: string;
        color?: string;
        tabids: string[];
        activetabid: string;
    };

    // wshrpc.WorkspaceInfoData
    type WorkspaceInfoData = {
        windowid: string;
        workspacedata: Workspace;
    };

    // wshrpc.WshServerCommandMeta
    type WshServerCommandMeta = {
        commandtype: string;
    };

}

export {}
