// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

declare global {

    // wps.WaveEvent
    type WaveEventName =
        | "blockclose"
        | "controllerstatus"
        | "waveobj:update"
        | "blockfile"
        | "config"
        | "badge"
        | "agent:status"
        | "notify"
        | "openfile"
        | "agent:ask"
        | "jarvis:volunteer"
        | "system:slept"
        | "dag:child-done"
        | "dag:gate-open"
        | "dag:dag-blocked"
        | "dag:dag-complete"
        | "dag:task-spawned"
        | "dag:child-ask"
        | "dag:task-stalled"
        | "dag:task-retried"
        | "run:event"
    ;

    type WaveEvent = {
        event: WaveEventName;
        scopes?: string[];
        sender?: string;
        persist?: number;
        data?: unknown;
    } & (
        { event: "blockclose"; data?: string; } | 
        { event: "controllerstatus"; data?: BlockControllerRuntimeStatus; } | 
        { event: "waveobj:update"; data?: WaveObjUpdate; } | 
        { event: "blockfile"; data?: WSFileEventData; } | 
        { event: "config"; data?: WatcherUpdate; } | 
        { event: "badge"; data?: BadgeEvent; } | 
        { event: "agent:status"; data?: AgentStatusData; } | 
        { event: "notify"; data?: NotifyCommandData; } | 
        { event: "openfile"; data?: OpenFileData; } | 
        { event: "agent:ask"; data?: AgentAskData; } | 
        { event: "jarvis:volunteer"; data?: VolunteerData; } | 
        { event: "system:slept"; data?: SleptData; } | 
        { event: "dag:child-done"; data?: string; } | 
        { event: "dag:gate-open"; data?: string; } | 
        { event: "dag:dag-blocked"; data?: string; } | 
        { event: "dag:dag-complete"; data?: string; } | 
        { event: "dag:task-spawned"; data?: string; } | 
        { event: "dag:child-ask"; data?: string; } | 
        { event: "dag:task-stalled"; data?: string; } | 
        { event: "dag:task-retried"; data?: string; } | 
        { event: "run:event"; data?: RunEventData; }
    );

}

export {}
