// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import { WshClient } from "./wshclient";

export interface MockRpcClient {
    mockWshRpcCall(client: WshClient, command: string, data: any, opts?: RpcOpts): Promise<any>;
    mockWshRpcStream(client: WshClient, command: string, data: any, opts?: RpcOpts): AsyncGenerator<any, void, boolean>;
}

// WshServerCommandToDeclMap
export class RpcApiType {
    mockClient: MockRpcClient = null;

    setMockRpcClient(client: MockRpcClient): void {
        this.mockClient = client;
    }

    // command "acceptdossieredge" [call]
    AcceptDossierEdgeCommand(client: WshClient, data: CommandDossierEdgeData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "acceptdossieredge", data, opts);
        return client.wshRpcCall("acceptdossieredge", data, opts);
    }

    // command "ackrun" [call]
    AckRunCommand(client: WshClient, data: CommandAckRunData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "ackrun", data, opts);
        return client.wshRpcCall("ackrun", data, opts);
    }

    // command "advancerun" [call]
    AdvanceRunCommand(client: WshClient, data: CommandAdvanceRunData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "advancerun", data, opts);
        return client.wshRpcCall("advancerun", data, opts);
    }

    // command "agentaskclear" [call]
    AgentAskClearCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "agentaskclear", data, opts);
        return client.wshRpcCall("agentaskclear", data, opts);
    }

    // command "agentcontrol" [responsestream]
	AgentControlCommand(client: WshClient, data: CommandAgentControlData, opts?: RpcOpts): AsyncGenerator<AgentControlMsg, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "agentcontrol", data, opts);
        return client.wshRpcStream("agentcontrol", data, opts);
    }

    // command "agentsyncadopt" [call]
    AgentSyncAdoptCommand(client: WshClient, data: CommandAgentSyncAdoptData, opts?: RpcOpts): Promise<CommandAgentSyncAdoptRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "agentsyncadopt", data, opts);
        return client.wshRpcCall("agentsyncadopt", data, opts);
    }

    // command "agentsyncapply" [call]
    AgentSyncApplyCommand(client: WshClient, data: CommandAgentSyncApplyData, opts?: RpcOpts): Promise<CommandAgentSyncApplyRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "agentsyncapply", data, opts);
        return client.wshRpcCall("agentsyncapply", data, opts);
    }

    // command "agentsyncskills" [call]
    AgentSyncSkillsCommand(client: WshClient, opts?: RpcOpts): Promise<CommandAgentSyncSkillsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "agentsyncskills", null, opts);
        return client.wshRpcCall("agentsyncskills", null, opts);
    }

    // command "agentsyncstatus" [call]
    AgentSyncStatusCommand(client: WshClient, opts?: RpcOpts): Promise<CommandAgentSyncStatusRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "agentsyncstatus", null, opts);
        return client.wshRpcCall("agentsyncstatus", null, opts);
    }

    // command "agentsyncsteeringread" [call]
    AgentSyncSteeringReadCommand(client: WshClient, opts?: RpcOpts): Promise<CommandAgentSyncSteeringReadRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "agentsyncsteeringread", null, opts);
        return client.wshRpcCall("agentsyncsteeringread", null, opts);
    }

    // command "agentsyncsteeringwrite" [call]
    AgentSyncSteeringWriteCommand(client: WshClient, data: CommandAgentSyncSteeringWriteData, opts?: RpcOpts): Promise<CommandAgentSyncSteeringWriteRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "agentsyncsteeringwrite", data, opts);
        return client.wshRpcCall("agentsyncsteeringwrite", data, opts);
    }

    // command "answeragent" [call]
    AnswerAgentCommand(client: WshClient, data: CommandAnswerAgentData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "answeragent", data, opts);
        return client.wshRpcCall("answeragent", data, opts);
    }

    // command "appenddossierdecision" [call]
    AppendDossierDecisionCommand(client: WshClient, data: CommandAppendDossierDecisionData, opts?: RpcOpts): Promise<CommandAppendDossierDecisionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "appenddossierdecision", data, opts);
        return client.wshRpcCall("appenddossierdecision", data, opts);
    }

    // command "ask" [call]
    AskCommand(client: WshClient, data: CommandAskData, opts?: RpcOpts): Promise<AskRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "ask", data, opts);
        return client.wshRpcCall("ask", data, opts);
    }

    // command "authenticate" [call]
    AuthenticateCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticate", data, opts);
        return client.wshRpcCall("authenticate", data, opts);
    }

    // command "authenticatetoken" [call]
    AuthenticateTokenCommand(client: WshClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticatetoken", data, opts);
        return client.wshRpcCall("authenticatetoken", data, opts);
    }

    // command "authenticatetokenverify" [call]
    AuthenticateTokenVerifyCommand(client: WshClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticatetokenverify", data, opts);
        return client.wshRpcCall("authenticatetokenverify", data, opts);
    }

    // command "blockslist" [call]
    BlocksListCommand(client: WshClient, data: BlocksListRequest, opts?: RpcOpts): Promise<BlocksListEntry[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "blockslist", data, opts);
        return client.wshRpcCall("blockslist", data, opts);
    }

    // command "cancelradarscan" [call]
    CancelRadarScanCommand(client: WshClient, data: CommandCancelRadarScanData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "cancelradarscan", data, opts);
        return client.wshRpcCall("cancelradarscan", data, opts);
    }

    // command "cancelrun" [call]
    CancelRunCommand(client: WshClient, data: CommandCancelRunData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "cancelrun", data, opts);
        return client.wshRpcCall("cancelrun", data, opts);
    }

    // command "canvasserve" [call]
    CanvasServeCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvasserve", data, opts);
        return client.wshRpcCall("canvasserve", data, opts);
    }

    // command "consult" [responsestream]
	ConsultCommand(client: WshClient, data: CommandConsultData, opts?: RpcOpts): AsyncGenerator<ConsultChunk, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "consult", data, opts);
        return client.wshRpcStream("consult", data, opts);
    }

    // command "controllerappendoutput" [call]
    ControllerAppendOutputCommand(client: WshClient, data: CommandControllerAppendOutputData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controllerappendoutput", data, opts);
        return client.wshRpcCall("controllerappendoutput", data, opts);
    }

    // command "controllerdestroy" [call]
    ControllerDestroyCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controllerdestroy", data, opts);
        return client.wshRpcCall("controllerdestroy", data, opts);
    }

    // command "controllerinput" [call]
    ControllerInputCommand(client: WshClient, data: CommandBlockInputData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controllerinput", data, opts);
        return client.wshRpcCall("controllerinput", data, opts);
    }

    // command "controllerresync" [call]
    ControllerResyncCommand(client: WshClient, data: CommandControllerResyncData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controllerresync", data, opts);
        return client.wshRpcCall("controllerresync", data, opts);
    }

    // command "createblock" [call]
    CreateBlockCommand(client: WshClient, data: CommandCreateBlockData, opts?: RpcOpts): Promise<ORef> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createblock", data, opts);
        return client.wshRpcCall("createblock", data, opts);
    }

    // command "createchannel" [call]
    CreateChannelCommand(client: WshClient, data: CommandCreateChannelData, opts?: RpcOpts): Promise<Channel> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createchannel", data, opts);
        return client.wshRpcCall("createchannel", data, opts);
    }

    // command "createchildrun" [call]
    CreateChildRunCommand(client: WshClient, data: CommandCreateChildRunData, opts?: RpcOpts): Promise<CommandCreateChildRunRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createchildrun", data, opts);
        return client.wshRpcCall("createchildrun", data, opts);
    }

    // command "createproject" [call]
    CreateProjectCommand(client: WshClient, data: CommandCreateProjectData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createproject", data, opts);
        return client.wshRpcCall("createproject", data, opts);
    }

    // command "createrun" [call]
    CreateRunCommand(client: WshClient, data: CommandCreateRunData, opts?: RpcOpts): Promise<CommandCreateRunRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createrun", data, opts);
        return client.wshRpcCall("createrun", data, opts);
    }

    // command "createworktree" [call]
    CreateWorktreeCommand(client: WshClient, data: CommandCreateWorktreeData, opts?: RpcOpts): Promise<CommandCreateWorktreeRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createworktree", data, opts);
        return client.wshRpcCall("createworktree", data, opts);
    }

    // command "dagaction" [call]
    DagActionCommand(client: WshClient, data: CommandDagActionData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dagaction", data, opts);
        return client.wshRpcCall("dagaction", data, opts);
    }

    // command "daganswer" [call]
    DagAnswerCommand(client: WshClient, data: CommandDagAnswerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "daganswer", data, opts);
        return client.wshRpcCall("daganswer", data, opts);
    }

    // command "dagasks" [call]
    DagAsksCommand(client: WshClient, data: CommandDagStatusData, opts?: RpcOpts): Promise<CommandDagAsksRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dagasks", data, opts);
        return client.wshRpcCall("dagasks", data, opts);
    }

    // command "dagmerge" [call]
    DagMergeCommand(client: WshClient, data: CommandDagMergeData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dagmerge", data, opts);
        return client.wshRpcCall("dagmerge", data, opts);
    }

    // command "dagmergecontinue" [call]
    DagMergeContinueCommand(client: WshClient, data: CommandDagMergeData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dagmergecontinue", data, opts);
        return client.wshRpcCall("dagmergecontinue", data, opts);
    }

    // command "dagplanpreview" [call]
    DagPlanPreviewCommand(client: WshClient, data: CommandDagPlanPreviewData, opts?: RpcOpts): Promise<CommandDagPlanPreviewRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dagplanpreview", data, opts);
        return client.wshRpcCall("dagplanpreview", data, opts);
    }

    // command "dagstatus" [call]
    DagStatusCommand(client: WshClient, data: CommandDagStatusData, opts?: RpcOpts): Promise<CommandDagStatusRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dagstatus", data, opts);
        return client.wshRpcCall("dagstatus", data, opts);
    }

    // command "dagsubmit" [call]
    DagSubmitCommand(client: WshClient, data: CommandDagSubmitData, opts?: RpcOpts): Promise<TaskGroup> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dagsubmit", data, opts);
        return client.wshRpcCall("dagsubmit", data, opts);
    }

    // command "deleteblock" [call]
    DeleteBlockCommand(client: WshClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "deleteblock", data, opts);
        return client.wshRpcCall("deleteblock", data, opts);
    }

    // command "deletechannel" [call]
    DeleteChannelCommand(client: WshClient, data: CommandDeleteChannelData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "deletechannel", data, opts);
        return client.wshRpcCall("deletechannel", data, opts);
    }

    // command "deleteproject" [call]
    DeleteProjectCommand(client: WshClient, data: CommandDeleteProjectData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "deleteproject", data, opts);
        return client.wshRpcCall("deleteproject", data, opts);
    }

    // command "detachdossieredge" [call]
    DetachDossierEdgeCommand(client: WshClient, data: CommandDossierEdgeData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "detachdossieredge", data, opts);
        return client.wshRpcCall("detachdossieredge", data, opts);
    }

    // command "doccompile" [call]
    DocCompileCommand(client: WshClient, data: CommandDocCompileData, opts?: RpcOpts): Promise<CommandDocCompileRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "doccompile", data, opts);
        return client.wshRpcCall("doccompile", data, opts);
    }

    // command "effortcreate" [call]
    EffortCreateCommand(client: WshClient, data: CommandEffortCreateData, opts?: RpcOpts): Promise<CommandEffortCreateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "effortcreate", data, opts);
        return client.wshRpcCall("effortcreate", data, opts);
    }

    // command "effortdelete" [call]
    EffortDeleteCommand(client: WshClient, data: CommandEffortDeleteData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "effortdelete", data, opts);
        return client.wshRpcCall("effortdelete", data, opts);
    }

    // command "effortget" [call]
    EffortGetCommand(client: WshClient, data: CommandEffortGetData, opts?: RpcOpts): Promise<CommandEffortGetRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "effortget", data, opts);
        return client.wshRpcCall("effortget", data, opts);
    }

    // command "effortlist" [call]
    EffortListCommand(client: WshClient, data: CommandEffortListData, opts?: RpcOpts): Promise<CommandEffortListRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "effortlist", data, opts);
        return client.wshRpcCall("effortlist", data, opts);
    }

    // command "effortmutate" [call]
    EffortMutateCommand(client: WshClient, data: CommandEffortMutateData, opts?: RpcOpts): Promise<CommandEffortMutateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "effortmutate", data, opts);
        return client.wshRpcCall("effortmutate", data, opts);
    }

    // command "eventpublish" [call]
    EventPublishCommand(client: WshClient, data: WaveEvent, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventpublish", data, opts);
        return client.wshRpcCall("eventpublish", data, opts);
    }

    // command "eventreadhistory" [call]
    EventReadHistoryCommand(client: WshClient, data: CommandEventReadHistoryData, opts?: RpcOpts): Promise<WaveEvent[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventreadhistory", data, opts);
        return client.wshRpcCall("eventreadhistory", data, opts);
    }

    // command "eventrecv" [call]
    EventRecvCommand(client: WshClient, data: WaveEvent, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventrecv", data, opts);
        return client.wshRpcCall("eventrecv", data, opts);
    }

    // command "eventsub" [call]
    EventSubCommand(client: WshClient, data: SubscriptionRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventsub", data, opts);
        return client.wshRpcCall("eventsub", data, opts);
    }

    // command "eventunsub" [call]
    EventUnsubCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventunsub", data, opts);
        return client.wshRpcCall("eventunsub", data, opts);
    }

    // command "filecreate" [call]
    FileCreateCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filecreate", data, opts);
        return client.wshRpcCall("filecreate", data, opts);
    }

    // command "filedelete" [call]
    FileDeleteCommand(client: WshClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filedelete", data, opts);
        return client.wshRpcCall("filedelete", data, opts);
    }

    // command "fileinfo" [call]
    FileInfoCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "fileinfo", data, opts);
        return client.wshRpcCall("fileinfo", data, opts);
    }

    // command "filejoin" [call]
    FileJoinCommand(client: WshClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filejoin", data, opts);
        return client.wshRpcCall("filejoin", data, opts);
    }

    // command "filemkdir" [call]
    FileMkdirCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filemkdir", data, opts);
        return client.wshRpcCall("filemkdir", data, opts);
    }

    // command "filemove" [call]
    FileMoveCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filemove", data, opts);
        return client.wshRpcCall("filemove", data, opts);
    }

    // command "fileread" [call]
    FileReadCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<FileData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "fileread", data, opts);
        return client.wshRpcCall("fileread", data, opts);
    }

    // command "filewrite" [call]
    FileWriteCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filewrite", data, opts);
        return client.wshRpcCall("filewrite", data, opts);
    }

    // command "getagenttranscript" [call]
    GetAgentTranscriptCommand(client: WshClient, data: CommandGetAgentTranscriptData, opts?: RpcOpts): Promise<CommandGetAgentTranscriptRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getagenttranscript", data, opts);
        return client.wshRpcCall("getagenttranscript", data, opts);
    }

    // command "getallbadges" [call]
    GetAllBadgesCommand(client: WshClient, opts?: RpcOpts): Promise<BadgeEvent[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getallbadges", null, opts);
        return client.wshRpcCall("getallbadges", null, opts);
    }

    // command "getattention" [call]
    GetAttentionCommand(client: WshClient, opts?: RpcOpts): Promise<CommandGetAttentionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getattention", null, opts);
        return client.wshRpcCall("getattention", null, opts);
    }

    // command "getbackgroundagents" [call]
    GetBackgroundAgentsCommand(client: WshClient, data: CommandGetBackgroundAgentsData, opts?: RpcOpts): Promise<CommandGetBackgroundAgentsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getbackgroundagents", data, opts);
        return client.wshRpcCall("getbackgroundagents", data, opts);
    }

    // command "getcachestatus" [call]
    GetCacheStatusCommand(client: WshClient, data: CommandGetCacheStatusData, opts?: RpcOpts): Promise<CommandGetCacheStatusRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getcachestatus", data, opts);
        return client.wshRpcCall("getcachestatus", data, opts);
    }

    // command "getchannelmessages" [call]
    GetChannelMessagesCommand(client: WshClient, data: CommandGetChannelMessagesData, opts?: RpcOpts): Promise<CommandGetChannelMessagesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getchannelmessages", data, opts);
        return client.wshRpcCall("getchannelmessages", data, opts);
    }

    // command "getchannelruns" [call]
    GetChannelRunsCommand(client: WshClient, data: CommandGetChannelRunsData, opts?: RpcOpts): Promise<CommandGetChannelRunsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getchannelruns", data, opts);
        return client.wshRpcCall("getchannelruns", data, opts);
    }

    // command "getchannels" [call]
    GetChannelsCommand(client: WshClient, opts?: RpcOpts): Promise<CommandGetChannelsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getchannels", null, opts);
        return client.wshRpcCall("getchannels", null, opts);
    }

    // command "getclaudequota" [call]
    GetClaudeQuotaCommand(client: WshClient, opts?: RpcOpts): Promise<CommandGetClaudeQuotaRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getclaudequota", null, opts);
        return client.wshRpcCall("getclaudequota", null, opts);
    }

    // command "getdossier" [call]
    GetDossierCommand(client: WshClient, data: CommandGetDossierData, opts?: RpcOpts): Promise<DossierDetail> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getdossier", data, opts);
        return client.wshRpcCall("getdossier", data, opts);
    }

    // command "getfullconfig" [call]
    GetFullConfigCommand(client: WshClient, opts?: RpcOpts): Promise<FullConfigType> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getfullconfig", null, opts);
        return client.wshRpcCall("getfullconfig", null, opts);
    }

    // command "getglobalprofile" [call]
    GetGlobalProfileCommand(client: WshClient, opts?: RpcOpts): Promise<JarvisProfile> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getglobalprofile", null, opts);
        return client.wshRpcCall("getglobalprofile", null, opts);
    }

    // command "getjarvisprofile" [call]
    GetJarvisProfileCommand(client: WshClient, data: CommandGetJarvisProfileData, opts?: RpcOpts): Promise<CommandGetJarvisProfileRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getjarvisprofile", data, opts);
        return client.wshRpcCall("getjarvisprofile", data, opts);
    }

    // command "getlatestresume" [call]
    GetLatestResumeCommand(client: WshClient, opts?: RpcOpts): Promise<CommandGetLatestResumeRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getlatestresume", null, opts);
        return client.wshRpcCall("getlatestresume", null, opts);
    }

    // command "getmeta" [call]
    GetMetaCommand(client: WshClient, data: CommandGetMetaData, opts?: RpcOpts): Promise<MetaType> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getmeta", data, opts);
        return client.wshRpcCall("getmeta", data, opts);
    }

    // command "getrecentsessions" [call]
    GetRecentSessionsCommand(client: WshClient, data: CommandGetRecentSessionsData, opts?: RpcOpts): Promise<CommandGetRecentSessionsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getrecentsessions", data, opts);
        return client.wshRpcCall("getrecentsessions", data, opts);
    }

    // command "getrtinfo" [call]
    GetRTInfoCommand(client: WshClient, data: CommandGetRTInfoData, opts?: RpcOpts): Promise<ObjRTInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getrtinfo", data, opts);
        return client.wshRpcCall("getrtinfo", data, opts);
    }

    // command "getsecretsnames" [call]
    GetSecretsNamesCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getsecretsnames", null, opts);
        return client.wshRpcCall("getsecretsnames", null, opts);
    }

    // command "getsessiongroup" [call]
    GetSessionGroupCommand(client: WshClient, data: CommandGetSessionGroupData, opts?: RpcOpts): Promise<CommandGetSessionGroupRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getsessiongroup", data, opts);
        return client.wshRpcCall("getsessiongroup", data, opts);
    }

    // command "getsessionsactivity" [call]
    GetSessionsActivityCommand(client: WshClient, data: CommandGetSessionsActivityData, opts?: RpcOpts): Promise<CommandGetSessionsActivityRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getsessionsactivity", data, opts);
        return client.wshRpcCall("getsessionsactivity", data, opts);
    }

    // command "getsubagents" [call]
    GetSubagentsCommand(client: WshClient, data: CommandGetSubagentsData, opts?: RpcOpts): Promise<CommandGetSubagentsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getsubagents", data, opts);
        return client.wshRpcCall("getsubagents", data, opts);
    }

    // command "gettranscripttokens" [call]
    GetTranscriptTokensCommand(client: WshClient, data: CommandGetTranscriptTokensData, opts?: RpcOpts): Promise<CommandGetTranscriptTokensRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gettranscripttokens", data, opts);
        return client.wshRpcCall("gettranscripttokens", data, opts);
    }

    // command "gettranscriptusage" [call]
    GetTranscriptUsageCommand(client: WshClient, data: CommandGetTranscriptUsageData, opts?: RpcOpts): Promise<CommandGetTranscriptUsageRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gettranscriptusage", data, opts);
        return client.wshRpcCall("gettranscriptusage", data, opts);
    }

    // command "getusagestats" [call]
    GetUsageStatsCommand(client: WshClient, data: CommandGetUsageStatsData, opts?: RpcOpts): Promise<CommandGetUsageStatsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getusagestats", data, opts);
        return client.wshRpcCall("getusagestats", data, opts);
    }

    // command "getwindowtokens" [call]
    GetWindowTokensCommand(client: WshClient, data: CommandGetWindowTokensData, opts?: RpcOpts): Promise<CommandGetWindowTokensRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getwindowtokens", data, opts);
        return client.wshRpcCall("getwindowtokens", data, opts);
    }

    // command "gitchanges" [call]
    GitChangesCommand(client: WshClient, data: CommandGitChangesData, opts?: RpcOpts): Promise<CommandGitChangesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitchanges", data, opts);
        return client.wshRpcCall("gitchanges", data, opts);
    }

    // command "gitcommitchanges" [call]
    GitCommitChangesCommand(client: WshClient, data: CommandGitCommitChangesData, opts?: RpcOpts): Promise<CommandGitCommitChangesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitcommitchanges", data, opts);
        return client.wshRpcCall("gitcommitchanges", data, opts);
    }

    // command "gitcomparechanges" [call]
    GitCompareChangesCommand(client: WshClient, data: CommandGitCompareChangesData, opts?: RpcOpts): Promise<CommandGitCompareChangesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitcomparechanges", data, opts);
        return client.wshRpcCall("gitcomparechanges", data, opts);
    }

    // command "gitdivergence" [call]
    GitDivergenceCommand(client: WshClient, data: CommandGitDivergenceData, opts?: RpcOpts): Promise<CommandGitDivergenceRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitdivergence", data, opts);
        return client.wshRpcCall("gitdivergence", data, opts);
    }

    // command "gitfetch" [call]
    GitFetchCommand(client: WshClient, data: CommandGitFetchData, opts?: RpcOpts): Promise<CommandGitFetchRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitfetch", data, opts);
        return client.wshRpcCall("gitfetch", data, opts);
    }

    // command "gitfileatref" [call]
    GitFileAtRefCommand(client: WshClient, data: CommandGitFileAtRefData, opts?: RpcOpts): Promise<CommandGitFileAtRefRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitfileatref", data, opts);
        return client.wshRpcCall("gitfileatref", data, opts);
    }

    // command "gitgrep" [call]
    GitGrepCommand(client: WshClient, data: CommandGitGrepData, opts?: RpcOpts): Promise<CommandGitGrepRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitgrep", data, opts);
        return client.wshRpcCall("gitgrep", data, opts);
    }

    // command "githistory" [call]
    GitHistoryCommand(client: WshClient, data: CommandGitHistoryData, opts?: RpcOpts): Promise<CommandGitHistoryRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "githistory", data, opts);
        return client.wshRpcCall("githistory", data, opts);
    }

    // command "gitlistfiles" [call]
    GitListFilesCommand(client: WshClient, data: CommandGitListFilesData, opts?: RpcOpts): Promise<CommandGitListFilesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitlistfiles", data, opts);
        return client.wshRpcCall("gitlistfiles", data, opts);
    }

    // command "gitlistignoreddir" [call]
    GitListIgnoredDirCommand(client: WshClient, data: CommandGitListIgnoredDirData, opts?: RpcOpts): Promise<CommandGitListIgnoredDirRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitlistignoreddir", data, opts);
        return client.wshRpcCall("gitlistignoreddir", data, opts);
    }

    // command "gitlistworktrees" [call]
    GitListWorktreesCommand(client: WshClient, data: CommandGitListWorktreesData, opts?: RpcOpts): Promise<CommandGitListWorktreesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitlistworktrees", data, opts);
        return client.wshRpcCall("gitlistworktrees", data, opts);
    }

    // command "gitrevert" [call]
    GitRevertCommand(client: WshClient, data: CommandGitRevertData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitrevert", data, opts);
        return client.wshRpcCall("gitrevert", data, opts);
    }

    // command "gitreviewpatch" [call]
    GitReviewPatchCommand(client: WshClient, data: CommandGitReviewPatchData, opts?: RpcOpts): Promise<CommandGitReviewPatchRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gitreviewpatch", data, opts);
        return client.wshRpcCall("gitreviewpatch", data, opts);
    }

    // command "jarvisctx" [call]
    JarvisCtxCommand(client: WshClient, data: CommandJarvisCtxData, opts?: RpcOpts): Promise<CommandJarvisCtxRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jarvisctx", data, opts);
        return client.wshRpcCall("jarvisctx", data, opts);
    }

    // command "jarvisrunevents" [call]
    JarvisRunEventsCommand(client: WshClient, data: CommandJarvisRunEventsData, opts?: RpcOpts): Promise<CommandJarvisRunEventsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jarvisrunevents", data, opts);
        return client.wshRpcCall("jarvisrunevents", data, opts);
    }

    // command "jarvisstate" [call]
    JarvisStateCommand(client: WshClient, data: CommandJarvisStateData, opts?: RpcOpts): Promise<CommandJarvisStateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jarvisstate", data, opts);
        return client.wshRpcCall("jarvisstate", data, opts);
    }

    // command "jarvisstatus" [call]
    JarvisStatusCommand(client: WshClient, data: CommandJarvisStatusData, opts?: RpcOpts): Promise<CommandJarvisStatusRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jarvisstatus", data, opts);
        return client.wshRpcCall("jarvisstatus", data, opts);
    }

    // command "landrun" [call]
    LandRunCommand(client: WshClient, data: CommandLandRunData, opts?: RpcOpts): Promise<RunLand> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "landrun", data, opts);
        return client.wshRpcCall("landrun", data, opts);
    }

    // command "listbranches" [call]
    ListBranchesCommand(client: WshClient, data: CommandListBranchesData, opts?: RpcOpts): Promise<CommandListBranchesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "listbranches", data, opts);
        return client.wshRpcCall("listbranches", data, opts);
    }

    // command "listdetachededges" [call]
    ListDetachedEdgesCommand(client: WshClient, data: CommandListDetachedEdgesData, opts?: RpcOpts): Promise<CommandListDetachedEdgesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "listdetachededges", data, opts);
        return client.wshRpcCall("listdetachededges", data, opts);
    }

    // command "listdossiers" [call]
    ListDossiersCommand(client: WshClient, opts?: RpcOpts): Promise<CommandListDossiersRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "listdossiers", null, opts);
        return client.wshRpcCall("listdossiers", null, opts);
    }

    // command "listharnesses" [call]
    ListHarnessesCommand(client: WshClient, opts?: RpcOpts): Promise<CommandListHarnessesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "listharnesses", null, opts);
        return client.wshRpcCall("listharnesses", null, opts);
    }

    // command "listradarreports" [call]
    ListRadarReportsCommand(client: WshClient, data: CommandListRadarReportsData, opts?: RpcOpts): Promise<CommandListRadarReportsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "listradarreports", data, opts);
        return client.wshRpcCall("listradarreports", data, opts);
    }

    // command "listtaskdossiers" [call]
    ListTaskDossiersCommand(client: WshClient, opts?: RpcOpts): Promise<CommandListTaskDossiersRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "listtaskdossiers", null, opts);
        return client.wshRpcCall("listtaskdossiers", null, opts);
    }

    // command "message" [call]
    MessageCommand(client: WshClient, data: CommandMessageData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "message", data, opts);
        return client.wshRpcCall("message", data, opts);
    }

    // command "notify" [call]
    NotifyCommand(client: WshClient, data: NotifyCommandData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "notify", data, opts);
        return client.wshRpcCall("notify", data, opts);
    }

    // command "path" [call]
    PathCommand(client: WshClient, data: PathCommandData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "path", data, opts);
        return client.wshRpcCall("path", data, opts);
    }

    // command "postchannelmessage" [call]
    PostChannelMessageCommand(client: WshClient, data: CommandPostChannelMessageData, opts?: RpcOpts): Promise<ChannelMessage> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "postchannelmessage", data, opts);
        return client.wshRpcCall("postchannelmessage", data, opts);
    }

    // command "readvaultnote" [call]
    ReadVaultNoteCommand(client: WshClient, data: CommandReadVaultNoteData, opts?: RpcOpts): Promise<CommandReadVaultNoteRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "readvaultnote", data, opts);
        return client.wshRpcCall("readvaultnote", data, opts);
    }

    // command "refreshroutecatalog" [call]
    RefreshRouteCatalogCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "refreshroutecatalog", null, opts);
        return client.wshRpcCall("refreshroutecatalog", null, opts);
    }

    // command "remotefilecopy" [call]
    RemoteFileCopyCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilecopy", data, opts);
        return client.wshRpcCall("remotefilecopy", data, opts);
    }

    // command "remotefiledelete" [call]
    RemoteFileDeleteCommand(client: WshClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefiledelete", data, opts);
        return client.wshRpcCall("remotefiledelete", data, opts);
    }

    // command "remotefileinfo" [call]
    RemoteFileInfoCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefileinfo", data, opts);
        return client.wshRpcCall("remotefileinfo", data, opts);
    }

    // command "remotefilejoin" [call]
    RemoteFileJoinCommand(client: WshClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilejoin", data, opts);
        return client.wshRpcCall("remotefilejoin", data, opts);
    }

    // command "remotefilemove" [call]
    RemoteFileMoveCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilemove", data, opts);
        return client.wshRpcCall("remotefilemove", data, opts);
    }

    // command "remotefilestream" [call]
    RemoteFileStreamCommand(client: WshClient, data: CommandRemoteFileStreamData, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilestream", data, opts);
        return client.wshRpcCall("remotefilestream", data, opts);
    }

    // command "remotelistentries" [responsestream]
	RemoteListEntriesCommand(client: WshClient, data: CommandRemoteListEntriesData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "remotelistentries", data, opts);
        return client.wshRpcStream("remotelistentries", data, opts);
    }

    // command "remotemkdir" [call]
    RemoteMkdirCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotemkdir", data, opts);
        return client.wshRpcCall("remotemkdir", data, opts);
    }

    // command "remotewritefile" [call]
    RemoteWriteFileCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotewritefile", data, opts);
        return client.wshRpcCall("remotewritefile", data, opts);
    }

    // command "removebackgroundagent" [call]
    RemoveBackgroundAgentCommand(client: WshClient, data: CommandRemoveBackgroundAgentData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "removebackgroundagent", data, opts);
        return client.wshRpcCall("removebackgroundagent", data, opts);
    }

    // command "reportrunphase" [call]
    ReportRunPhaseCommand(client: WshClient, data: CommandReportRunPhaseData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "reportrunphase", data, opts);
        return client.wshRpcCall("reportrunphase", data, opts);
    }

    // command "resolveambient" [call]
    ResolveAmbientCommand(client: WshClient, opts?: RpcOpts): Promise<CommandResolveAmbientRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "resolveambient", null, opts);
        return client.wshRpcCall("resolveambient", null, opts);
    }

    // command "resolvedossieredges" [call]
    ResolveDossierEdgesCommand(client: WshClient, data: CommandResolveDossierEdgesData, opts?: RpcOpts): Promise<CommandResolveDossierEdgesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "resolvedossieredges", data, opts);
        return client.wshRpcCall("resolvedossieredges", data, opts);
    }

    // command "resolvefocusscope" [call]
    ResolveFocusScopeCommand(client: WshClient, data: CommandResolveFocusScopeData, opts?: RpcOpts): Promise<SpaceScope> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "resolvefocusscope", data, opts);
        return client.wshRpcCall("resolvefocusscope", data, opts);
    }

    // command "resolveids" [call]
    ResolveIdsCommand(client: WshClient, data: CommandResolveIdsData, opts?: RpcOpts): Promise<CommandResolveIdsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "resolveids", data, opts);
        return client.wshRpcCall("resolveids", data, opts);
    }

    // command "retryradarclustering" [call]
    RetryRadarClusteringCommand(client: WshClient, data: CommandRetryRadarClusteringData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "retryradarclustering", data, opts);
        return client.wshRpcCall("retryradarclustering", data, opts);
    }

    // command "routeannounce" [call]
    RouteAnnounceCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "routeannounce", null, opts);
        return client.wshRpcCall("routeannounce", null, opts);
    }

    // command "routeunannounce" [call]
    RouteUnannounceCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "routeunannounce", null, opts);
        return client.wshRpcCall("routeunannounce", null, opts);
    }

    // command "runanswer" [call]
    RunAnswerCommand(client: WshClient, data: CommandRunAnswerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "runanswer", data, opts);
        return client.wshRpcCall("runanswer", data, opts);
    }

    // command "runasks" [call]
    RunAsksCommand(client: WshClient, data: CommandRunAskData, opts?: RpcOpts): Promise<CommandDagAsksRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "runasks", data, opts);
        return client.wshRpcCall("runasks", data, opts);
    }

    // command "runtranscriptpath" [call]
    RunTranscriptPathCommand(client: WshClient, data: CommandRunTranscriptPathData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "runtranscriptpath", data, opts);
        return client.wshRpcCall("runtranscriptpath", data, opts);
    }

    // command "runusage" [call]
    RunUsageCommand(client: WshClient, data: CommandRunUsageData, opts?: RpcOpts): Promise<CommandRunUsageRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "runusage", data, opts);
        return client.wshRpcCall("runusage", data, opts);
    }

    // command "scanclaudeprojects" [call]
    ScanClaudeProjectsCommand(client: WshClient, opts?: RpcOpts): Promise<CommandScanClaudeProjectsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "scanclaudeprojects", null, opts);
        return client.wshRpcCall("scanclaudeprojects", null, opts);
    }

    // command "sealrunevidence" [call]
    SealRunEvidenceCommand(client: WshClient, data: CommandSealRunEvidenceData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "sealrunevidence", data, opts);
        return client.wshRpcCall("sealrunevidence", data, opts);
    }

    // command "setchannelprofile" [call]
    SetChannelProfileCommand(client: WshClient, data: CommandSetChannelProfileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setchannelprofile", data, opts);
        return client.wshRpcCall("setchannelprofile", data, opts);
    }

    // command "setchannelread" [call]
    SetChannelReadCommand(client: WshClient, data: CommandSetChannelReadData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setchannelread", data, opts);
        return client.wshRpcCall("setchannelread", data, opts);
    }

    // command "setchanneltier" [call]
    SetChannelTierCommand(client: WshClient, data: CommandSetChannelTierData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setchanneltier", data, opts);
        return client.wshRpcCall("setchanneltier", data, opts);
    }

    // command "setconfig" [call]
    SetConfigCommand(client: WshClient, data: SettingsType, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setconfig", data, opts);
        return client.wshRpcCall("setconfig", data, opts);
    }

    // command "setdossierstatus" [call]
    SetDossierStatusCommand(client: WshClient, data: CommandSetDossierStatusData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setdossierstatus", data, opts);
        return client.wshRpcCall("setdossierstatus", data, opts);
    }

    // command "setglobalprofile" [call]
    SetGlobalProfileCommand(client: WshClient, data: CommandSetGlobalProfileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setglobalprofile", data, opts);
        return client.wshRpcCall("setglobalprofile", data, opts);
    }

    // command "setmeta" [call]
    SetMetaCommand(client: WshClient, data: CommandSetMetaData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setmeta", data, opts);
        return client.wshRpcCall("setmeta", data, opts);
    }

    // command "setpeerinfo" [call]
    SetPeerInfoCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setpeerinfo", data, opts);
        return client.wshRpcCall("setpeerinfo", data, opts);
    }

    // command "setradarfindingdisposition" [call]
    SetRadarFindingDispositionCommand(client: WshClient, data: CommandSetRadarFindingDispositionData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setradarfindingdisposition", data, opts);
        return client.wshRpcCall("setradarfindingdisposition", data, opts);
    }

    // command "setrtinfo" [call]
    SetRTInfoCommand(client: WshClient, data: CommandSetRTInfoData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setrtinfo", data, opts);
        return client.wshRpcCall("setrtinfo", data, opts);
    }

    // command "setrunsettings" [call]
    SetRunSettingsCommand(client: WshClient, data: CommandSetRunSettingsData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setrunsettings", data, opts);
        return client.wshRpcCall("setrunsettings", data, opts);
    }

    // command "setsecrets" [call]
    SetSecretsCommand(client: WshClient, data: {[key: string]: string}, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setsecrets", data, opts);
        return client.wshRpcCall("setsecrets", data, opts);
    }

    // command "startradarscan" [call]
    StartRadarScanCommand(client: WshClient, data: CommandStartRadarScanData, opts?: RpcOpts): Promise<CommandStartRadarScanRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "startradarscan", data, opts);
        return client.wshRpcCall("startradarscan", data, opts);
    }

    // command "stoprunworker" [call]
    StopRunWorkerCommand(client: WshClient, data: CommandStopRunWorkerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "stoprunworker", data, opts);
        return client.wshRpcCall("stoprunworker", data, opts);
    }

    // command "streamagenttranscript" [responsestream]
	StreamAgentTranscriptCommand(client: WshClient, data: CommandStreamAgentTranscriptData, opts?: RpcOpts): AsyncGenerator<AgentTranscriptUpdate, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "streamagenttranscript", data, opts);
        return client.wshRpcStream("streamagenttranscript", data, opts);
    }

    // command "streamdata" [call]
    StreamDataCommand(client: WshClient, data: CommandStreamData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "streamdata", data, opts);
        return client.wshRpcCall("streamdata", data, opts);
    }

    // command "streamdataack" [call]
    StreamDataAckCommand(client: WshClient, data: CommandStreamAckData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "streamdataack", data, opts);
        return client.wshRpcCall("streamdataack", data, opts);
    }

    // command "termgetscrollbacklines" [call]
    TermGetScrollbackLinesCommand(client: WshClient, data: CommandTermGetScrollbackLinesData, opts?: RpcOpts): Promise<CommandTermGetScrollbackLinesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "termgetscrollbacklines", data, opts);
        return client.wshRpcCall("termgetscrollbacklines", data, opts);
    }

    // command "uiinvoke" [call]
    UiInvokeCommand(client: WshClient, data: CommandUiInvokeData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "uiinvoke", data, opts);
        return client.wshRpcCall("uiinvoke", data, opts);
    }

    // command "uireveal" [call]
    UiRevealCommand(client: WshClient, data: CommandUiRevealData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "uireveal", data, opts);
        return client.wshRpcCall("uireveal", data, opts);
    }

    // command "uistate" [call]
    UiStateCommand(client: WshClient, opts?: RpcOpts): Promise<UiState> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "uistate", null, opts);
        return client.wshRpcCall("uistate", null, opts);
    }

    // command "updateworkspacetabids" [call]
    UpdateWorkspaceTabIdsCommand(client: WshClient, arg1: string, arg2: string[], opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "updateworkspacetabids", { args: [arg1, arg2] }, opts);
        return client.wshRpcCall("updateworkspacetabids", { args: [arg1, arg2] }, opts);
    }

    // command "vaultgraph" [call]
    VaultGraphCommand(client: WshClient, opts?: RpcOpts): Promise<CommandVaultGraphRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "vaultgraph", null, opts);
        return client.wshRpcCall("vaultgraph", null, opts);
    }

    // command "vaultsetremote" [call]
    VaultSetRemoteCommand(client: WshClient, data: CommandVaultSetRemoteData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "vaultsetremote", data, opts);
        return client.wshRpcCall("vaultsetremote", data, opts);
    }

    // command "vaultstatus" [call]
    VaultStatusCommand(client: WshClient, opts?: RpcOpts): Promise<VaultStatusRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "vaultstatus", null, opts);
        return client.wshRpcCall("vaultstatus", null, opts);
    }

    // command "vaultsync" [call]
    VaultSyncCommand(client: WshClient, data: CommandVaultSyncData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "vaultsync", data, opts);
        return client.wshRpcCall("vaultsync", data, opts);
    }

    // command "waveinfo" [call]
    WaveInfoCommand(client: WshClient, opts?: RpcOpts): Promise<WaveInfoData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "waveinfo", null, opts);
        return client.wshRpcCall("waveinfo", null, opts);
    }

    // command "workspacelist" [call]
    WorkspaceListCommand(client: WshClient, opts?: RpcOpts): Promise<WorkspaceInfoData[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "workspacelist", null, opts);
        return client.wshRpcCall("workspacelist", null, opts);
    }

    // command "writetempfile" [call]
    WriteTempFileCommand(client: WshClient, data: CommandWriteTempFileData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "writetempfile", data, opts);
        return client.wshRpcCall("writetempfile", data, opts);
    }

}

export const RpcApi = new RpcApiType();
